### ISSUE TITLE
Theme / Custom colors

### ISSUE THREAD

**Issue by GiroSA** [stsrki/Blazorise#101]
I have been trying to find a way to specify my own color scheme (theme) in an easy way. If I don't want the default color for Primary, Secondary etc. how do I change it without changing it everywhere in material.css.

Is this possible? How?

**Comment by stsrki** [comment]
There are a couple ways how you can do that. All of them have pros ans cons.

1. Use the _.scss_ from [daemonite](http://daemonite.github.io/material/docs/4.1/getting-started/theming/) site to override default colors and build your own css files. This way you will still be able to use Blazorise colors.
2. Change material.css styles in your own _site.css_ or whatever your main css is called. 
3. Create you own custom css classes for every element and apply them through the Blazorise `Class` attribute that can be found on every component.
4. If you would go with 3rd option you can inherit `MaterialClassProvider `and override predefined classnames used by the Blazorise. For example if you want to use `my-btn-red` instead of default `btn-primary` then you can override `ButtonColor()` function.

It's not easy I know but until I figure best way to handle theming this is how you do it.

**Comment by GiroSA** [comment]
Noted. Thanks.
