### ISSUE TITLE
Whole layout overlay

### ISSUE THREAD

**Issue by akusmin** [stsrki/Blazorise#1084]
For server app it is not possible to collect from a local storage information regarding authorization token so it is required to wait for rendering finished to collect data from local storage and execute authorization. For a user it is Login page flushing (if stored token is valid) before accessing navigation page.

Is it possible to support build-in layout overlay with visibility property binding or triggering Show/Toggle method so it can be shown for example in case of loading or error placeholder?

**Comment by stsrki** [comment]
I think this would go beyond what Blazorise goal is. And that is to be an UI framework. What you have described is specific to authentication and your use-case specifically. I don't have in plan to implement anything regarding non UI within Blazorise. Sorry

**Comment by MitchellNZ** [comment]
@stsrki I agree that authentication is definitely stepping outside Blazorise goal!
However, I don't think its a bad idea to provide the tools to do this overlay!

I am happy to implement a simple overlay loading action for the `Layout` component.
I was thinking like:
```
<Layout @bind-Loading="loading">
...
</Layout>

@code {
    private bool loading = true;
    ....
}
```
This would just create a semi-transparent overlay so that use couldn't click anything until its toggled.

@akusmin would this allow you to achieve your goal?

**Comment by MitchellNZ** [comment]
Additionally, I plan on working on a loading "skeleton" (see https://github.com/stsrki/Blazorise/issues/1086).

**Comment by stsrki** [comment]
@MitchellNZ I like it. It would be good to have additional template parameter so that users could add something like animation or progress bar on top of overlay. For me `Loading `indicates some kind of animation.

**Comment by akusmin** [comment]
@MitchellNZ yes. It's exactly what I'm talking about. Thanks!
