### ISSUE TITLE
Changing chart options?

### ISSUE THREAD

**Issue by janellesnowy** [stsrki/Blazorise#109]
Hi, I'm trying to change the font color on the chart axes, and I noticed there is only SetOptions, I can't modify existing options as it is protected. I have resetup quite a lot of things just to modify the font color.

**Comment by stsrki** [comment]
The `Options` is protected because that was a constraint in the older versions of Blazor. Components could be created with only private and protected properties. I think in the latest versions they enabled properties so they can be public but I think they are still rethinking that. Until they figure it and made it final I will not risk to change API for Blazorise components. So they will stay protected for now.

Also there is another reason for `SetOptions` instead of `Options` parameter. That is to prevent unnecessary re-initialization and calls to javascript on every page refresh in case there was any `StateHasChanged`. That's why you should call the `SetOptions` manually. I could maybe reconsider and see if anything could be done to prevent that after the release of Blazor preview 6 where they will finally release new Json serializer for JSInterop calls.

**Comment by RoyRosenberg** [comment]
Hi,
I noticed a **OptionsJsonString** property, can I change the legend position with that? I tried 
`<PieChart OptionsJsonString="{legend: {'position' : 'left'}"  @ref="pieChart" TItem="double" />`
but without help...

**Comment by stsrki** [comment]
**OptionsJsonString** and **DataJsonString** are used to manually send json to the chartjs component. They were introduced because Blazor serializer was really bad at that time. 

You can use it but keep in mind that once the default Blazor serializer is fixed, OptionsJsonString will be removed from Blazorised.

Also I think you're missing closing **}** from the json:
`<PieChart OptionsJsonString="{legend: {'position' : 'left'}}" @ref="pieChart" TItem="double" />`

**Comment by stsrki** [comment]
Closing the issue as I think the original problem is now solved. All parameters have public access modifiers. If you need more help please reopen.
