### ISSUE TITLE
CheckEdit (CSS): "cursor" should be "pointer"

### ISSUE THREAD

**Issue by Garios** [stsrki/Blazorise#114]
Hello,
the current cursor is an arrow. This should be a pointer. I think the label has the wrong value.

**Comment by stsrki** [comment]
I guess you're talking about bootstrap implementation? This is the default behavior for bootstrap, [see](https://getbootstrap.com/docs/4.3/components/forms/#checkboxes-and-radios)
It seems that Bulma is setting a pointer, [see](https://bulma.io/documentation/form/checkbox/)

Maybe I could add some property so developers can chose pointer type but I think best way is to leave it as it is. This way developers can define it manually with Class property and some custom css.

**Comment by Garios** [comment]
Sry, I mean Material-Design:
https://material.io/design/components/text-fields.html

**Comment by stsrki** [comment]
Current material implementation for Blazorise is based on [daemonite](http://daemonite.github.io/material/) which is basically a bootstrap theme based on material design principles. When I started Blazorise this was the easiest for me to implement. Since the development of daemonite has stopped lately I've being thinking to implement the _real_ material based on material.io
It will be a lot of work so it is not going to be that fast.

**Comment by Garios** [comment]
My current workaround is:

```
.custom-checkbox > .custom-control-label {
     cursor: pointer !important;
}
```

perhaps, it could help you.
