### ISSUE TITLE
TextEdit AutoComplete Attribute Support

### ISSUE THREAD

**Issue by longhornleads** [stsrki/Blazorise#1246]
**Is your feature request related to a problem? Please describe.**
I don't see anyway to support Google Chrome's autofill for say addresses using TextEdit which our users are constantly asking for.  Which basically means we have to not use Blazorize for those components.

**Describe the solution you'd like**
Add support for all of the autofill properties (add the AutoComplete attribute) to TextEdit

**Comment by stsrki** [comment]
Did you tried Autocomplete component ?

https://blazorise.com/docs/extensions/autocomplete/

**Comment by stsrki** [comment]
@JonWright53 I tried to do that a few months ago #3363, but unfortunately wasn0t possible at the time. Based on my investigation it cannot be disabled by any means. If you happen to know the solution I'm open to any advice.

**Comment by David-Moreira** [comment]
Well... that's not what  @longhornleads wrote...
he clearly says 

"I don't see **anyway to support Google Chrome's autofill** for say addresses"

![image](https://user-images.githubusercontent.com/22283161/183046034-481beb7f-c8de-4421-b7b2-537b509090f7.png)
![image](https://user-images.githubusercontent.com/22283161/183046140-92f10503-cfed-4a96-840e-ad1977e91c56.png)

----------------

So I don't see why you guys are talking about disabling it? If we already support it because it's a native behaviour, then it's all good for @longhornleads request?

**Comment by stsrki** [comment]
I will correct myself. Instead of _disabled_, it should say _control_. There is no good way to control the auto-fill without the browser standing in the way.
