### ISSUE TITLE
The Blazorise demo webpage is loading too long

### ISSUE THREAD

**Issue by iwis** [stsrki/Blazorise#1317]
When I first opened the https://bootstrapdemo.blazorise.com/ site, it loaded in about 10 seconds on my mobile phone. When I load it again, it seems to load faster, but **still takes about 5 seconds**. I thought that Blazor should load longer only the first time.

On my notebook it takes about **1-2 second so it is also too long**.

I have a Samsung Galaxy S7 phone and a [Dell Latitude 5580 notebook](https://icecat.biz/en/p/dell/n002l558015emea/latitude-notebooks-5901165766303-5580-35779598.html).

The loading looks like this:

![Blazorise](https://user-images.githubusercontent.com/8080496/93452924-4c4e1a00-f8d9-11ea-9fb4-fc40b8da24db.png)

I would expect that the next views of the https://bootstrapdemo.blazorise.com/ webpage after the first initial view should happen immediately.

I posted this question also on [Reddit/r/Blazor](https://www.reddit.com/r/Blazor/comments/iorby5/why_is_blazor_loading_so_long/).

PS. Thank you for this great initiative!

**Comment by stsrki** [comment]
It takes 2 or 3 seconds for me. Maybe it depends on what browser you're using. I'm using a chrome on my phone.

Also 10 seconds is indeed too long and I never experienced that long loading. Could be that the demo app on my server was down so it had to startup. I will investigate.

**Comment by iwis** [comment]
I also use the newest Google Chrome both on my smartphone and my notebook.

This loading time (10s) when I display the page for the first time is less important, than the following times. On Reddit someone said that the CPU load is high during the page is loaded. If I understand correctly, then the next time I visit https://bootstrapdemo.blazorise.com all libraries should be in cache of the web browser. Because the GUI isn't too complicated visually, and Blazorise doesn't process thousands of records, one can expect that the website should be displayed instantly on subsequent visits. Why is this not happening?

**Comment by iwis** [comment]
I believe that the page is loading 5-10 s on my smartphone because it is 4 years old, and its CPU is probably several times slower than yours. But in my opinion the second more important reason is that https://bootstrapdemo.blazorise.com/ performs some CPU intensive work every time it is opened in a web browser.

**Comment by stsrki** [comment]
It's unfortunately just how WebAssembly apps are working, they always need to download something and only after all the resource are downloaded it will start the app. And this is all happening on the client side. Hence the spike in CPU. With prerendering mode enabled this would lover the loading times but that requires some more work to setup the apps. Which I plan to do sometime.

For example you can see a server-side version of demo app with prerendering enabled, Loading time is faster and there is no CPU spike since in this case everything is running on server. https://rcbootstrapdemo.blazorise.com/

**Comment by iwis** [comment]
Time of 2nd, 3rd, 4th loading*) of the web page on Samsung Galaxy S7:
 - https://bootstrapdemo.blazorise.com/   - 5 seconds (too long)
 - https://rcbootstrapdemo.blazorise.com/ - 2 seconds (acceptable, could be better for ex. 1s)

Time of 2nd, 3rd, 4th, ... loading**) of the web page on my laptop:
 - https://bootstrapdemo.blazorise.com/   - 2 seconds (acceptable, could be better for ex. 1s)
 - https://rcbootstrapdemo.blazorise.com/ - about 1.2 second (good, could be better for ex. 1s)

*)  - on smartphone I swipe down in Google Chrome to refresh the web page
**) - on laptop I press right mouse button on the Google Chrome tab and choose "Duplicate" menu item

So https://rcbootstrapdemo.blazorise.com/ load faster than https://bootstrapdemo.blazorise.com/ - the load times are acceptable in my opinion both on mobile and computer. Unfortunately, Blazor Server **is suitable only for intranet apps or for apps with few users so it isn't an option in most popular cases**.

**Comment by iwis** [comment]
> It's unfortunately just how WebAssembly apps are working, they always need to download something
Even if I view the page for the 2nd, 3rd, 4th time? Why?

Disclaimer: I newer used React/Angualr/Vue so I don't know how it should work.

**Comment by LukeTOBrien** [comment]
That's why God invented the `F12 Dev Tools`.  
Check out the network tab 👇 
![Blazorise-demo-network](https://user-images.githubusercontent.com/16164373/95012619-fa73f680-0631-11eb-89f7-8828c3192376.png)

Unfortunately there are some things that you cannot control, `dotnet.wasm` is about 2MB and there's nothing you can do about that, `System.Core` and `System` are necessary as well.  
There may be some things that you might be able to remove, `System.Drawing.Common` might not be necessary and there might be other things you can do without.

So all in all it's about 7MB and thankfully your app might not get much bigger than that. 
I managed find a lot of unessary dependancies and realised `Newtonsoft.Json` also pulls in `System.Xml`, so I replaced this with `System.Text.Json`.  
My app is about 10MB and takes 11 seconds to download.

You will just have to create a really awesome app, then your users wont mind waiting for all that awesomeness 😉

**Comment by LukeTOBrien** [comment]
Also just to say that the other day I found a nice [blog post about profiling](https://remibou.github.io/Profiling-in-Blazor/).  
this chap had created a nice little [NuGet package](https://www.nuget.org/packages/BrowserInterop) that can help you find out where bottle-necks are in your app.

**Comment by stsrki** [comment]
@LukeTOBrien Thanks for explaining it. You did a really good job. Also, nice find with the blog post about profiling!

**Comment by LukeTOBrien** [comment]
Thanks! great project.
I guess you can close this issue now.

**Comment by iwis** [comment]
@LukeTOBrien, @stsrki: I do not understand the results. What was the problem? Why the issue was closed?

**Comment by stsrki** [comment]
@iwis As @LukeTOBrien already explained there is no problem. At least not with Blazorise. The _issue_ is with Blazor and how it works. Specifically how it needs to download all the DLL's prior to the first actual rendering happens. If you would run the basic Blazor template you would get the same result. 

As far as I see it, there is no way around it.

**Comment by iwis** [comment]
It seems that you forgot that I was writing about opening the page not for the 1st time but for the second, third and later times. In my opinion everything should be in the cache. So there is problem because some CPU intensive work.

**Comment by iwis** [comment]
And of course it is a problem, and nothing was explained because downloading time has nothing to do here.

**Comment by iwis** [comment]
It seems that you both forgot that I wasn't writing about opening the page for the 1st time, but for the 2nd time, 3rd time and later.

From the 2nd time almost everything is cached. @LukeTOBrien made a mistake because he clicked on the "Disable cache" checkbox, but it should be unchecked. Please see my screnshot. If you uncheck this checkbox you see that only 3.2kB are transferred in milliseconds. But still the whole process takes 3.38 seconds because Blazor or Blazorise is doing some redundant CPU intensive work, maybe it is the same problem I described in https://github.com/stsrki/Blazorise/issues/1341.

So there is a problem, Blazor downloads no DLLs, @LukeTOBrien haven't explained the problem, so the issue should be reopened.

![Blazorise](https://user-images.githubusercontent.com/8080496/95028291-90923600-069f-11eb-82e0-af625f300236.png)

**Comment by stsrki** [comment]
Hi @iwis sorry if I gave you an impression of ignoring you. That was not my goal at all. The thing is that I felt that I already answered your question(s) and gave you a valid reason why the initialization is slow.

To give you more context I will post a couple of links to other WebAssembly demo apps that I found on the web.

- https://blazor-wasm.quarella.net/
- https://blazorwithidentity.azurewebsites.net/login

The first example since it is really complex takes for me over 4 seconds. The second example while fairly basic it takes almost a second. Both of them are WebAssembly and not server-side apps. This leads me to conclude that even though everything is already cached the rendering will always be slow in the current state of Blazor WebAssembly, no matter how small the app is. I agree that Blazorise can be optimized, and that is in the plan, which I already mentioned on #1341. The optimizations are planned for v0.9.3.

I hope by now I answered your questions :) please let me know if you need anything else.

**Comment by LukeTOBrien** [comment]
When .Net 5 comes out, I'm sure the demos will be upgraded to that version
and then we will see if there is a difference.

Web Assembly is near machine language, but Blazor projects are DLLs and
depend on DLLs, even if they are cached they still need to be
interpreted by the dotnet.wasm
I don't know the internal workings of dotnet.wasm, but I would say that
interpreting the DLLs is what is taking the time.
Wasm also has no DOM access, so I would guess that after the DLLs are
interpreted, the resulting HTML is is added to the page using JavaScript
(dotnet.3.2.js)

The profiling article I linked to is more important, because when you
create an app you will find that your own code matters more then the
framework,
In my app I had my page load at 50 seconds, I did profiling and found some
XHR request being fired unnecessarily, await preventing render and events
not being removed on Dispose... I got it back down to 10 seconds.

Anyway, my closing remark still stands, build an app that you users want to
use and they won't mind waiting a few seconds if it is worth it.
It depends on your audience, business users are more patient and they won't
mind waiting.

**Comment by iwis** [comment]
Ok, now it is clear.
However, I don't agree with LukeTOBrien that it is ok to wait for a webpage - a web page should load as fast as possible, Blazor/Webassembly preferably should load at least as fast as React/Vue/Angular/JavaScript applications. For sure being several times slower isn't good, because it means that for users it is better if we used JavaScript instead of Blazor Wasm.
One of the main difference between Blazor and Javascript apps that I notice is that Blazor apps display a web page only after all the processing is finished, earlier they only display some loading icon, or a text like: "Loading ...", "Loading BlazorBoilderplate (CSB) ...", etc. On the other hand, traditional JavaScript pages (for example https://www.reddit.com/) display a part of the page even if the processing still isn't finished, so a use is able to read it content earlier. Thus, any performance lags are even more visible in Blazor than in traditional web pages.

I attached screenshots of network and performance analyses of the loading of the aforementioned websites for the 2nd time (so some resources are already cached):

1. https://blazor-wasm.quarella.net/  - 274 kB downloaded, scripting time: 7.1 s

![Quarella Network](https://user-images.githubusercontent.com/8080496/95068069-0b416c80-0705-11eb-8fe9-fbf0ce9827dc.png)
![Quarella CPU](https://user-images.githubusercontent.com/8080496/95068084-12687a80-0705-11eb-9f03-2174bcdf3156.png)


2. https://blazorwithidentity.azurewebsites.net/login - 4 kB downloaded, scripting time: 1.6 s

![Blazorwithidentity Network](https://user-images.githubusercontent.com/8080496/95068057-05e42200-0705-11eb-882d-8351c6bf0ea5.png)
![Blazorwithidentity CPU](https://user-images.githubusercontent.com/8080496/95068060-07ade580-0705-11eb-9fe8-89c8ee8c1779.png)

**Comment by LukeTOBrien** [comment]
JavaScript frameworks like Vue et al use JS + Html/CSS  
Blazor is Wasm(C#/DLL) + JS + Html/CSS  
So Blazor will always be slower (I'm afraid) due to the initial Wasm bit - Wasm cannot manipulate the DOM and so JS is needed to append the output Html to the page.  
The fact that Blazor might be slower is the responsibility of Microsoft, the Mono team and .Net community.

The advantages (and  there are many) is heavy processing, maintainability and NuGet.  In my project I am using [Markdig](https://github.com/lunet-io/markdig) and [HTML Agility Pack](https://html-agility-pack.net/), so this is heavy server-side processing that can now be done in the browser.

Users will certainly wait if it's something they want.  
How long are you prepared to wait in a queue to iced donut?  
So concentrate on making an app that users want and worry about performance at the end 😉

**Comment by iwis** [comment]
Here is a comparison of loading times of Blazor vs other JS frameworks: https://github.com/dotnet/aspnetcore/issues/21085#issuecomment-650820274

In this thread people also think that Blazor will be slower than JS framework in the future.

> How long are you prepared to wait in a queue to get an iced donut?

I don't know, maybe 10 minutes. It depends on many factors. But if there will be another shorter queue I prefer to not wait in the longer one.

> [**Is WebAssembly trying to replace JavaScript?**](https://webassembly.org/docs/faq/#is-webassembly-trying-to-replace-javascript)
> No! WebAssembly is designed to be a complement to, not replacement of, JavaScript. While WebAssembly will, over time, allow many languages to be compiled to the Web, JavaScript has an incredible amount of momentum and will remain the single, privileged (as described above) dynamic language of the Web.
