### ISSUE TITLE
Support for stacked bar charts

### ISSUE THREAD

**Issue by jpacreb** [stsrki/Blazorise#1321]
I'm adding some charts to a project and will need to include some **Stacked** Bar Charts (preferably Horizontal).

I've tried getting the bars to stack without success, including deriving a new class from **Axis** and adding a boolean **Stacked** property (as Chart.js uses this for specifying stacked bar charts). 

Is there currently a way to stack the bars?  If not can this be added a feature for the future?

Thanks

Richard

**Comment by stsrki** [comment]
From what I can see it's only missing one property in the settings https://www.chartjs.org/docs/latest/charts/bar.html#stacked-bar-chart. It's not a problem to add. 

As a workaround, you can use `OptionsObject` parameter on the chart. You can set any options that way and it will serialize it instead of the default `Options` parameter.

**Comment by jpacreb** [comment]
Thanks @stsrki , I have used the OptionsObject as you suggested and that has (temporarily) solved the problem.
