### ISSUE TITLE
Side nav bar

### ISSUE THREAD

**Issue by ikkyGH** [stsrki/Blazorise#135]
Hey, great work so far.  These are awesome.  Are there any plans to implement a side navigation bar?  Much like the current <bar> control, but it would expand from the side.  Thanks in advance.

**Comment by stsrki** [comment]
There is already a Sidebar component and it is available on [NuGet](https://www.nuget.org/packages/Blazorise.Sidebar/). You can see the usage in the [demo app](https://github.com/stsrki/Blazorise/blob/master/Tests/Blazorise.Demo/Layouts/MainLayout.razor).

The reason why it's still not in the documentation is because I plan to clean and refactor it a little first. Probably in the version after **0.8**, that is after I finish theming support for Blazorise which is needed for this.

**Comment by ikkyGH** [comment]
that's awesome.  Thanks so much

**Comment by ikkyGH** [comment]
Last Question for today.  Is the side nav collapsible at all?

**Comment by stsrki** [comment]
Yes, you can see it in the demo also. It's used like this:

**Set the ref parameter:**
```
<Sidebar @ref="sidebar">
    ...
</Sidebar>
```
**Call Toggle on some action, maybe on button click:**
```
@code{
    Sidebar sidebar;

    void ToggleSidebar()
    {
        sidebar.Toggle();
    }
}
```

**Comment by ikkyGH** [comment]
thanks again
