### ISSUE TITLE
AutoComplete validation works off text rather than value

### ISSUE THREAD

**Issue by robalexclark** [stsrki/Blazorise#1350]
For a SelectList component, the e.Value in the ValidatorEventArgs has the value that is referenced by the ValueField parameter.

Autocomplete doesn't seem to work like this (?) The e.Value in the ValidatorEventArgs is from the Text entered rather than any actual selected value.

How do I validate that a valid value is selected in an autocomplete (and not just any text)

?

**Comment by stsrki** [comment]
Both SelectList and Autocomplete components are wrappers around existing components. So `SelectList` contains the `Select` and `Autocomplete` contains the `TextEdit`. Also, both SelectList and Autocomplete does not have their own validation. The actual validation is done on their wrapped components. And so, the reason why it's returning `Text` is because the TextEdit is doing all the work.

A agree it's strange that Autocomplete does not have its own validation. I'm not sure if it's going to work without rewriting the component.

**Comment by stsrki** [comment]
Note for me! Possible solutions for Autocomplete validation

- Remove TextEdit from Autocomplete and replace it with regular input
- Add new parameter on TextEdit called `ValidationDisabled`. This way we will not have two validators for the "same" Validation

**Comment by stsrki** [comment]
Madi it work with some internal changes and it works like this:

```cshtml
<Autocomplete TItem="MySelectModel"
                TValue="string"
                Data="@myDdlData"
                TextField="@((item)=>item.MyTextField)"
                ValueField="@((item)=>item.MyTextField)"
                SelectedValue="@selectedSearchValue"
                SelectedValueChanged="@MySearchHandler"
                Placeholder="Search..." Filter="AutocompleteFilter.StartsWith"
                Validator="IsValidValue">
</Autocomplete>
@code{
    void IsValidValue( ValidatorEventArgs e )
    {
        Console.WriteLine( e.Value );

        e.Status = !string.IsNullOrEmpty( e.Value?.ToString() ) && myDdlData.Any( x => x.MyTextField == e.Value.ToString() )
            ? ValidationStatus.Success
            : ValidationStatus.Error;

        if ( e.Status == ValidationStatus.Error )
        {
            e.ErrorText = "ERROR";
        }
        else
        {
            e.ErrorText = "OK";
        }
    }
}
```
