### ISSUE TITLE
SelectList - Ability to set the `Disabled` attribute

### ISSUE THREAD

**Issue by jaszb** [stsrki/Blazorise#1370]
It would be great to have the ability to bind a `Disabled` attribute a Blazorise SelectList's `Data` property so the item is available to be seen but not selectable/clickable.

This is a common scenario where apps have `Soft Delete` pattern

https://www.w3schools.com/TAGS/att_option_disabled.asp

I see we have this `Disabled` attribute on the `Select` component already - but unfortunately that component does not allow us to bind to a `Data` property to build the SelectItem array - so I have to use the `SelectList`

Thanks

**Comment by stsrki** [comment]
Hi. `SelectList` is just a simple wrapper around the `Select` component so you could just recreate a similar component for you your own scenario. That would be the easier and fastest route. eg

```cshtml
<Select TValue="int" @bind-SelectedValue="@selectedItemValue">
    @foreach(var item in yourList)
    {
        <SelectItem TValue="int" Value="@item.Value" disabled="@item.SomeFlag">@item.Name</SelectItem>
    }
</Select>
```

Notice I have set `disabled` attribute. It should work because Blazorise support attribute splitting so it will be applied to the underline element.

**Comment by jaszb** [comment]
perfect thanks
