### ISSUE TITLE
DataGrid with different model

### ISSUE THREAD

**Issue by angelru** [stsrki/Blazorise#1373]
I have a grid with data that is shared and others that are different depending on the type of data, for example: a patient can be (adult or minor) and will have some fields that will be different, but the data that is shown in the grid is shared . The problem here is that when I add a patient or edit based on type, it will have different fields, I cannot use the TItem element (because some fields are not the same). So far what I have done is a button to add patient with a picklist off the grid based on type and I show a modal, but I see that I am repeating data with this approach although I cannot find another alternative with blazorise. I can't have different pages depending on the type, everything has to go in the same one (to add adult or minor).

Is there a way to blazorize or implement in the future, for example by passing a model to a modal and generating it based on the object and fields?

**Comment by stsrki** [comment]
It's a pretty specific scenario so I don't think it will ever be possible natively with DataGrid. You could try with the base class for all your models, but then the problem is that you have different fields for every model type and that can be problematic.

You can look at this ticket #548 and see if it could work for you maybe.
