### ISSUE TITLE
DataGridCheckColumn

### ISSUE THREAD

**Issue by nulajo68** [stsrki/Blazorise#1379]
Hello,

I've used in a Datagrid a DataGridCheckColumn, but the values are not shown as Checkboxes. I Just see True or False instead of Checkboxes for these values.

Are checkboxes supported in the Datagrid or not?

Thanks in advance.
John

**Comment by stsrki** [comment]
When you define columns for DataGrid it's more to give it a clue how it will behave when in **Edit** mode. In the regular display mode, a DataGrid will always use `.ToString()` to display the actual cell value. That's why you're seeing the True or False for boolean.

There were talks about this in the past and I think it's best to leave it like it is now. And if you want to show something else, like an actual checkbox than you have an option to use `DisplayTemplate`.

**Example**

```cshtml
<DataGridCheckColumn TItem="Employee" Field="@nameof(Employee.IsActive)">
    <DisplayTemplate>
        <Check TValue="bool" Checked="context.IsActive" Disabled="true" ReadOnly="true" />
    </DisplayTemplate>
</DataGridCheckColumn>
```

**Comment by nulajo68** [comment]
Ha thank you, this works for me...
Is there more documentation for Blazorise beneath the Website?

**Comment by stsrki** [comment]
You mean besides the https://blazorise.com/docs/ ? The short answer is no. But you can always search for issues here and see. A lot of people usually have the same problems that are already solved.

Or if you think somethings missing in the documentation you can always contribute 😊

**Comment by nulajo68** [comment]
Thank you! In case of a problem of my knowledge, I will search here or ask here...
