### ISSUE TITLE
Allow translation for elements with text

### ISSUE THREAD

**Issue by AlexTeixeira** [stsrki/Blazorise#1445]
Hi, First many thanks for your work is this beautiful nuget package. I use it in 2 projects and it makes me win a lot of time.

### Missing feature 

I'm a French developer, and some component like File or DataGrid have some text that comes by default (browse for the file, pagination text for DataGrid).

Do you have already a solution to translate the text or planned to make on update to allow change the text of the components ?

### Needed solution

If you don't already have the solution, the solution is to be able to change the text or to update the template to be able to change the text.

### Screenshots

<img width="838" alt="image" src="https://user-images.githubusercontent.com/6555080/98515602-8d283680-226b-11eb-9557-d7e94ed64fa7.png">

<img width="888" alt="image" src="https://user-images.githubusercontent.com/6555080/98515656-a92bd800-226b-11eb-8c74-4c666b196631.png">

**Comment by stsrki** [comment]
You can use `CaptionTemplate` to handle the column header of DataGrid. But for other components like FileEdit, I still don't have a good approach. 

I have already implemented localization for `Validation` component messages and I will slowly do other components too.  That's something I plan to work on soon.

**Comment by AlexTeixeira** [comment]
Ok. I will have a look to CaptionTemplate. thanks

**Comment by Riedi2070** [comment]
Same problem with Pagination in DataGrids in a german web app. Tanslation feature for componentes would be very nice :)

![image](https://user-images.githubusercontent.com/5427990/99533093-9caf2a00-29a5-11eb-9c42-29597e60e2c1.png)

**Comment by stsrki** [comment]
@Riedi2070 Not at the moment. But it's planned to be done soon.

**Comment by stsrki** [comment]
Hello to everyone in this conversation. I'm currently working on a localization feature and I'm kinda stuck on which way to proceed.

## Idea 1

My first idea was to use `IStringLocalizer`([docs](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.localization.istringlocalizer?view=dotnet-plat-ext-3.1)). So far it works OK. But, the first problem with this solution is that I would need to add a package `Microsoft.Extensions.Localization`. Also, I would need to include embedded resources for every language. It's not a problem for a few languages but it can grow over time and it's not easy to configure. With this solution, the final Blazor app can be around 140KB larger which is kinda OK.

## Idea 2

My next idea is to create IComponentLocalizer, which looks like this:

```cs
public interface IComponentLocalizer
{
    string GetText( string key );

    string this[string key, string defaultText]
    {
        get;
    }
}
```

With this interface, I can create a default implementation that will return some texts from a dictionary. The good thing is that anyone can override their own implementation of `IComponentLocalizer`.

So, do you guys think any of this is good? Or have an idea for a better solution? Thanks

**Comment by araknusc** [comment]
It would be easy to stay with IStringLocalizer as that would stay inline with Microsoft implementation? I suppose if you include support one for two languages with the ability for people to add further resource files as per their need?

**Comment by stsrki** [comment]
@araknusc Yes, that was my first idea. But it's not very flexible. It also requires more configurations on application startup(setting culture info for `DefaultThreadCurrentCulture` and `DefaultThreadCurrentUICulture`). Not to mention that dynamically changing culture info also requires to restart the app. While doable I don't like all of the stuff that comes with it.

**Comment by araknusc** [comment]
yes, that is correct. The setup required is not easy to figure out with IStringLocalizer. I spent the whole day yesterday to get it working on my Blazor Wasm App. But after spending that time I find future management quite easy especially because there are quite a few resx maintenance tools. If the Blazor Wasm App already uses the resx implementation then maintaining another interface requires having the texts maintained in two places sometimes. But let's see what others say :).

**Comment by stsrki** [comment]
The same thing for me also. If it takes that long to even start using something, it's a red flag for me. It should have to be a lot easier. Anyways, as you said, let's see what others got to say.

**Comment by joseazevedo** [comment]
Idea 1 "is not easy to set up" is a red flag. 
I prefer Idea 2, just because it is simple and as you said, we can override it.

**Comment by stsrki** [comment]
Guys, a little overview of what I did so far. I have tried to use `IStringLocalizer` but whatever I did I couldn't make it work in WebAssembly project. I wanted to be able to change the language in runtime. As far as I know, this is currently not possible because `IStringLocalizer` caches everything on application start and can't refresh later on. If someone knows better please let me know.

## `ITextLocalizer`

So considering all the problems with `IStringLocalizer` I have decided to create a custom `ITextLocalizer`. The usage is the same as `IStringLocalizer`, eg. `Localizer["Choose files"]`.

### Features of new `ITextLocalizer`:

- all translations are done in JSON file (as embedded resource)
- translation can be retrieved dynamically based on the currently set culture
- can add custom translations through the `AddLanguageResource`
- Easier to setup the project than with `IStringLocalizer`

## `ITextLocalizerService`:

Along with `ITextLocalizer` I also created `ITextLocalizerService` that is used to change the current culture and notify the app components that culture has changed.

### Usage of `ITextLocalizerService`:

```cs
[Inject] ITextLocalizerService LocalizationService { get; set; }

protected override async Task OnInitializedAsync()
{
    await SelectCulture( "en-US" );

    await base.OnInitializedAsync();
}

Task SelectCulture( string name )
{
    LocalizationService.ChangeLanguage( name );

    return Task.CompletedTask;
}
```

Obviously, if anyone still wishes to use `IStringLocalizer` they can just implement their own `ITextLocalizer` and register it with dependency injection.

## Parameter?

One last thing that I want to add is to have maybe `LocalizationText` parameter on a Blazorise component so that for example we can have:

```cshtml
<FileEdit LocalizationText="My custom browse button" />
```
Once `LocalizationText` is defined it will have priority over `ITextLocalizer`.

So, what you guys think?

**Comment by AlexTeixeira** [comment]
Hi,

Sorry for the delay. I will look at this right now, but seems to resolve the big pictures for this issue. If I found some minors issue I open new ones :).

Thanks for your time 👍

**Comment by Jinjinov** [comment]
Could you update https://blazorise.com/docs/helpers/localization with a complete example on how to localize a custom page / component? It is hard to understand how we can do this, which variables and files we need and where to put them and how this scales to multiple custom components?
