### ISSUE TITLE
First Element in Chart grey on hower.

### ISSUE THREAD

**Issue by itsLollo1000** [stsrki/Blazorise#1458]
If you use any kind of Chart the first elements "hower color" in the chart gets grey. When not howered the color is correct to the data.

1. Go to the demo for charts (https://rcbootstrapdemo.blazorise.com/tests/charts)
2. Hower over any red Chart element.
4. See the color gets grayed.

![Bootstrap Demo - Google Chrome 12 11 2020 13_16_51](https://user-images.githubusercontent.com/10349466/98939214-5f502580-24e9-11eb-831a-0cecf8589d90.png)
![Bootstrap Demo - Google Chrome 12 11 2020 13_16_11](https://user-images.githubusercontent.com/10349466/98939212-5eb78f00-24e9-11eb-936d-719dc2705978.png)

**Comment by stsrki** [comment]
That's strange. And it only happens for the first element 🤔

Thanks for reporting!

**Comment by itsLollo1000** [comment]
Yes only for the first element.

No problem just found out! 😄

**Comment by Joelius300** [comment]
Since I saw that this is about the charting I thought I'd chime in and contribute to this great project :)  
Bear in mind that I'm only speaking from experience with `ChartJs.Blazor` and have not tested these points.

This seems to be a bigger issue and should be reproducible with many other options like the point background color, the point hover color, the hover border color, etc.

The reason for that is the following:
When you serialize any enumeration, you'll get an array in json. All those properties that I mentioned, are [indexable options](https://www.chartjs.org/docs/latest/general/options.html#indexable-options) which means that they will either apply the value directly to all elements if it's not an array or map the array to the data-values. In [`LineChartDataset`](https://github.com/stsrki/Blazorise/blob/93c016408b7a0f12b9014c6fc7dcdd779f8cbf6c/Source/Extensions/Blazorise.Charts/ChartData.cs#L97) and many other places, the default value of `new List<string> { ChartColor.FromRgba( 0, 0, 0, 0.1f ) }` is passed. However, this does NOT apply that color to all the values (like it would if it was just the string, not the list) but instead only to the first element.

The [IndexableOption](https://github.com/mariusmuntean/ChartJs.Blazor/blob/master/src/ChartJs.Blazor/Common/IndexableOption.cs) type used in `ChartJs.Blazor` is by no means perfect (it actually has quite a few issues) but it distinguishes between a singular value and an array of values which solves this problem.

However, this issue shows another thing which is quite important and that is that there will always be the same default value passed with that `0, 0, 0, 0.1f` color even when the Chart.js default says something different. To fix that, you'd have to omit that property on serialization.

These are just some notes, there are many ways to fix this.
