### ISSUE TITLE
DropDownList not showing the selected item

### ISSUE THREAD

**Issue by crisras27** [stsrki/Blazorise#1459]
**Describe the bug**
i am using the example dropdownlist on a blazor app and is not selecting the new itme keeps showing select item

**To Reproduce**
copy paste the example on blazor docs

**Expected behavior**
shows the selected item

![image](https://user-images.githubusercontent.com/28845341/98974033-0f1d9700-24da-11eb-8edd-328aac71f508.png)

![image](https://user-images.githubusercontent.com/28845341/98974068-1ba1ef80-24da-11eb-8374-24209fbf4bf2.png)

**Comment by stsrki** [comment]
Hi @crisras27. This is by design. DropdownList was never meant to show the selected item. From UX or UI standpoint, a dropdown is a menu with a limited amount of options to choose from.

In this example **Select item** is just a text to display on a toggle button.

```diff
<DropdownList Data="@myDdlData"
                TextField="@((item)=>item.MyTextField)"
                ValueField="@((item)=>item.MyValueField)"
                SelectedValue="@selectedDropValue"
                SelectedValueChanged="@MyDropValueChangedHandler"
                Color="Color.Primary">
+    Select item
</DropdownList>
```

Maybe a better option for you is to use the Select component?

**Comment by stsrki** [comment]
PS. if you want to replace "Select item" with the actual selected item you can just replace it with `@selectedDropValue`

```
<DropdownList ...>
    @selectedDropValue
</DropdownList>
```

**Comment by crisras27** [comment]
uhhh okey!!! thanks so much for the info!!! 

i got it!!!
