### ISSUE TITLE
Performance of form validation

### ISSUE THREAD

**Issue by realLiangshiwei** [stsrki/Blazorise#1499]
I found that form validation can cause performance problem in some cases

   1. When there are too many form items
   2. When using annotation verification and model verification

### How to reproduce the problem

Can easily reproduce this problem, Just open the demo page: https://bootstrapdemo.blazorise.com/tests/validations

![ng](https://user-images.githubusercontent.com/16813853/99874988-ea869500-2c26-11eb-908b-44999e3d4f9d.gif)

I quickly enter some values in input, You can see the delay of the input box. 

Using manual verification will get better performance, but adding more input will reduce performance

![image](https://user-images.githubusercontent.com/16813853/99875184-9086cf00-2c28-11eb-87c6-455d1ee69f0f.png)

![ng](https://user-images.githubusercontent.com/16813853/99875357-ec058c80-2c29-11eb-9679-e6cc29ada1f5.gif)

**Comment by stsrki** [comment]
It's a known limitation, especially in the server-side Blazor project. You can make it better by using `DelayTextOnKeyPress` and `DelayTextOnKeyPressInterval`, and if that doesn't help you can disable `ChangeTextOnKeyPress`.

`ChangeTextOnKeyPress` basically switches use of `@onchange` or `@oninput` events.

**Comment by Welchen** [comment]
@stsrki is this a Blazor limitation or Blazorise limitation?  

I was coming to make an issue about this myself. We deployed to a server and almost feels unusable because of the cursor not keeping up with the typing and typing out of order. Also when backspacing it feels like it is just deleting chunks.

**Comment by stsrki** [comment]
It's hard to tell really. Blazorise components are using `@oninput` or `@onchange`, whichever you choose. On input is the default option. 

Blazor on the other hand is using only `@onchange` so it will not have that problem since refresh is happening only once when input lost focus.

Blazorise also has a lot more components and features that all can affect refresh in a different way. 

So, currently, for server-side apps, it's best to disable `ChangeTextOnKeyPress`. Either globally or per component.

**Comment by realLiangshiwei** [comment]
Enabled DelayTextOnKeyPress will be useful,  but we should look into the reason in-depth

**Comment by stsrki** [comment]
I'm trying all the time to squeeze every possible optimization I can to speed it up. Hopefully one time I will be able to find a good solution.

**Comment by Welchen** [comment]
@realLiangshiwei  / @stsrki  I did try out  `DelayTextOnKeyPress` and that did help out my issues. 

I might have to eventually recode to WASM.

**Comment by stsrki** [comment]
I will close this now since I already have similar tickets open with the same problem.
