### ISSUE TITLE
Slow keydown event

### ISSUE THREAD

**Issue by 274188A** [stsrki/Blazorise#1528]
**Describe the bug**
I have an ABP project (Blazor Wasm version 4 rc4)

When a user tries to enter data via pressing keys on a keyboard while the focus is inside a TextEditor and there are more than 10 TextEditor controls on a page - the page is practically unusable because the delay in seeing the value typed in is so slow.
This occurs on published pages as well as running without debugger attached

**To Reproduce**
1. Create a Blazor page with > 10 controls
2. Ensure they have "@bind=text" to some data model
3. Observe the delay in responsiveness

**Expected behavior**
Faster response to key down events when a user is typing into a particular control 

**Typical TextEdit Control used**
```
<TextEdit @bind-text="@EditingEntity.Name" MaxLength="255" />

```
**Browser Tools Showing Slow Event**
![image](https://user-images.githubusercontent.com/40014477/100195433-4bb5ad80-2f32-11eb-8657-e84b4291e571.png)

**Comment by stsrki** [comment]
If you don't need real-time text change you can disable `ChangeTextOnKeyPress`.

**Example**

`<TextEdit @bind-Text="@EditingEntity.Name" MaxLength="255" ChangeTextOnKeyPress="false"  />`

The `ChangeTextOnKeyPress="false"` will tell TextEdit to use `@onchange` instead of `@ininput`.

PS. You also had `@bind-text` instead of `@bind-Text`, it should always be uppercase.

**Comment by 274188A** [comment]
personally I think the default should be `ChangeTextOnKeyPress="false"`
