### ISSUE TITLE
.Net core 3 preview 7 support

### ISSUE THREAD

**Issue by aford22** [stsrki/Blazorise#156]
Now that preview 7 is out, when can we expect Blazorise support?

Thank you :-)

**Comment by stsrki** [comment]
Currently working on `DataGrid` component which is going to be finished in the next few days. It is the last thing left for **v0.8**. This version is going have some big improvements so I also have to test and document everything.
Since now preview 7 is available I will also include it in the release. I think by the end of this week everything will be ready. You'll have to wait just a little longer.

**Comment by aford22** [comment]
Wow - that’s impressive having p7 support in your next release! Well done :-). Also looking forward to the data grid component, that will be huge for many of us...

**Comment by stsrki** [comment]
Setting this here because this will be the tracking ticket;

https://devblogs.microsoft.com/aspnet/asp-net-core-and-blazor-updates-in-net-core-3-0-preview-7/
