### ISSUE TITLE
Dynamic sideBar

### ISSUE THREAD

**Issue by ikkyGH** [stsrki/Blazorise#157]
Hey.

I am reviewing from your example of how to use the SideBar component and had a question on the best approach to dynamically build it.  It would easy enough to iterate through a look and generate the SidebarItems, but how could I dynamically create and reference the relationship between the SideBarSubItem and the first SidebarLink to allow for the toggle?  Thanks in advance

![image](https://user-images.githubusercontent.com/35937046/61742212-9765af00-ad60-11e9-906d-9f9a367769e6.png)

**Comment by stsrki** [comment]
I can't test it now but I think you need to have just a few changes,

1. remove `IsShow="true"` from subitem because that is always going to reset your toggle state. Instead use the variable like `IsShow="@subItemOpened"`.
2. you don't need to send variable to the `Toggle `function. Just use it like `sidebarSubItemTests.Toggle()`

To dynamically create sidebar I will have to see what I can do. Probably in the version 0.8.1 or  0.8.2. I need to finish **v0.8** which is going to be by the end of this week if everything goes as planned.

**Comment by Suemo** [comment]
Thanks for adding that to the list.   While u are in there, can you look at making the sidebar have a “small” state.  Where it would be smaller, but not completely hidden.  Just big enough to show some icons that would fly out the menu when selected?  Would be a nice UI feature.

Thanks in advance.

**Comment by stsrki** [comment]
Regarding your request for smaller state sidebar I would consider that for some future task. I plan to rewrite the sidebar anyway. For now I think dynamic creation will be the best solution.

If you want please open a new issue for the smaller sidebar.

**Comment by stsrki** [comment]
Done. The usage for dynamic building will be in the documentation.
