### ISSUE TITLE
Implement Ant Design ?

### ISSUE THREAD

**Issue by yehia2amer** [stsrki/Blazorise#163]
[Ant Design ](https://ant.design/)is one of the most used UI frameworks out there.
It is Enterprise Class with a minimalist design aesthetic and every component under the sun.

More about it: [Styling Applications with Ant.Design](https://medium.com/@yoniweisbrod/styling-react-applications-with-ant-design-92b742aab0b0).

Any Plans to Support it ?

**Comment by stsrki** [comment]
Technically almost every css framework could be implemented in Blazorise. For now I don't have plans to add Ant Design.
The reason is that I still change some Blazorise APIs so I don't want to have too many supported frameworks or otherwise it will become a hell to maintain it all. Also there is another reason why I didnt add other frameworks before and that is because they dont support full range of colors other than some basic like primary, danger, info etc. In the next v0.8 of Blazorise I will add support for themes so that kind of things will be easier to overcome.
I wanted to add Fluent design next and then Material from google. After that I will consider others like Ant.

**Comment by dan-motion** [comment]
Wow, I'd never really looked at Ant Design properly until now.  It's got a vast number of controls so it would be an epic undertaking to support them all.  If it's ever goes ahead, Blazorise would instantly become the most valuable component library on the planet!

If Microsoft had any sense they'd massively sponsor this project and provide a team to help out.

**Comment by stsrki** [comment]
@dan-motion I investigate a lot since the issue was opened and I feel like Ant Design should be the next provider implemented for Blazorise. It seems like most of the controls are already compatible.

Yeah that would be the best option to sponsor the project and help in some way. But I would also be grateful if they could at least mention Blazorise in one of their release notes. Most of the time they speak only about the commercial libraries.

**Comment by stsrki** [comment]
Setting here the resources and links as this is going to be a tracking ticket.

- https://ant.design/docs/spec/introduce
- https://ant.design/docs/react/introduce
- https://cdnjs.com/libraries/antd

**Comment by stsrki** [comment]
The new provider is done with PR #678

**Comment by MitchellNZ** [comment]
@stsrki Thanks very much for completing this! I'm very keen to start using it. 
Is there any chance you plan on doing a preview release to your MyGet feed?
Thanks!

**Comment by stsrki** [comment]
It's already up on MyGet.

**Comment by MitchellNZ** [comment]
@stsrki Great! Wasn't showing up before, but it is now. Thanks again!
