### ISSUE TITLE
NumericEdit doesn't have spinner buttons

### ISSUE THREAD

**Issue by Mijalski** [stsrki/Blazorise#1642]
**Issue:**
When creating a NumericEdit node I would assume it would have the spinner buttons present on the demo page.

**To reproduce:**
1. Create a node of Type NumericEdit (eg. NumericEdit Value="123" )
2. Open the web page with the node, observe the lack of spinner buttons

**Expected behavior**
Spinner buttons should be present, preferably it could be an option ShowSpinnerButtons on the node.

**Screenshots**
Screenshot from the [demo page](https://blazorise.com/docs/components/numeric/):
![obraz](https://user-images.githubusercontent.com/40124816/103008192-071f3100-4535-11eb-8a72-87b79bcc6419.png) 
My project (v 0.9.2.4): 
![obraz](https://user-images.githubusercontent.com/40124816/103008864-0dfa7380-4536-11eb-9c43-90a335d161b5.png)
![obraz](https://user-images.githubusercontent.com/40124816/103008920-279bbb00-4536-11eb-9ee1-16ff621154f9.png)
![obraz](https://user-images.githubusercontent.com/40124816/103008937-2ec2c900-4536-11eb-83a8-5f9432a64c49.png)

**Additional context**
Does not work with either Bootstrap or Empty provider.

**Comment by stsrki** [comment]
It's a known limitation. The problem is that NumericEdit is using `<input type="text"` to allow more control over string parsing and selections. With `<input type="number"` this was not possible. Pressing up/down keys still works but yeah, I agree spinner button would be great to have. At one point I might implement them, but for now, it's low on a priority list.

**Comment by Mijalski** [comment]
Would you mind explaining, why the buttons are there on the demo page?

**Comment by stsrki** [comment]
I don't see it

![image](https://user-images.githubusercontent.com/900302/103009164-937e2380-4536-11eb-8c79-ec96d36f6687.png)

What browser do you use?

**Comment by Mijalski** [comment]
https://blazorise.com/docs/components/numeric/

**Comment by stsrki** [comment]
Ahhh in the documentation. That's a whole another problem and needs a little more explanation :)

It involves a little history. When Blazorise was first created over two years ago, there was no server-side prerendering and all SEO features that we have today. So when I wanted to create documentation pages, I was limited with very bad and slow WebAssembly at the time. So I chose Jekyll as my static-site generator to be served from Github. As a result, all the examples are actually just a simple HTML and have nothing with Blazorise. And since then, Blazorise kind of blew up and I had little time to build new documentation in Blazorise.

But, lately, I'm building new Blazorise documentation that will be a real thing. It just takes time :)

**Comment by Mijalski** [comment]
Ok, that's why! I was confused about it.

**Comment by stsrki** [comment]
You're not the first 😅

**Comment by stsrki** [comment]
Close in favor of #1733
