### ISSUE TITLE
dev093: Validations :: Unhandled exception rendering component: The provided expression contains a InstanceMethodCallExpression1 which is not supported. FieldIdentifier only supports simple member accessors (fields, properties) of an object.

### ISSUE THREAD

**Issue by sks-ttaylor** [stsrki/Blazorise#1700]
**Describe the bug**
using Validations on a page with a Validator in a @foreach generates error
Unhandled exception rendering component: The provided expression contains a InstanceMethodCallExpression1 which is not supported. FieldIdentifier only supports simple member accessors (fields, properties) of an object.

**To Reproduce**

```

		@page "/"
		<Validations @ref="validations" Mode="ValidationMode.Manual">
		  <Container Fluid="true">
			@foreach (string phoneKey in Phones.Keys)
			{
			  <Row>
				<Column>
				  <Field Horizontal="true">
					<FieldLabel ColumnSize="ColumnSize.Is3">@phoneKey</FieldLabel>
					<FieldBody ColumnSize="ColumnSize.Is9">
					  <Validation UsePattern="true">
						<TextEdit @bind-Text="@Phones[phoneKey]"
								  MaskType="MaskType.RegEx"
								  EditMask="(^\d{0,3}$|^\d{3}-$|^\d{3}-\d{0,3}$|^\d{3}-\d{3}-$|^\d{3}-\d{3}-\d{0,4}$)"
								  Pattern="^[0-9][0-9][0-9]-[0-9][0-9][0-9]-[0-9][0-9][0-9][0-9]$" />
						<ValidationError>Invalid Phone Number</ValidationError>
					  </Validation>
					</FieldBody>
				  </Field>
				</Column>
			  </Row>
			}

		  </Container>
		</Validations>
		@code {
		  private Validations validations { get; set; }
		  private Dictionary<string, string> Phones { get; set; }
		  public override Task SetParametersAsync(ParameterView parameters)
		  
			Phones = new Dictionary<string, string>();
			Phones.Add("Mobile", "123-123-1234");
			Phones.Add("Business", null);
			Phones.Add("Mobile-2", "123-456-7890");
			Phones.Add("Business-2", null);

			return base.SetParametersAsync(parameters);
		  }
		}
		
```
		

**Expected behavior**
No error

**Comment by sks-ttaylor** [comment]
Further findings:::

if switch from @bind-Text to Text and TextChanged  it works...

**Comment by stsrki** [comment]
There are multiple things hapening here actually. You used `Validations` and `@bind-Text` on a (somewhat) complex object. Internally this triggers Blazorise into data-annotation mode for doing validations. But the problem is that `FieldIdentifier` doesn't work with array objects. This is the same as what Blazor team is using, so I guess it wouldn't work for regular Blazor components also.

So, I'm not sure what is the right thing to do here. I can surround it in a `try catch` block but that feels dirty. So I think it's best to go with your "workaround" for now.

**Comment by sks-ttaylor** [comment]
Thanks for confirming
