### ISSUE TITLE
NumericEdit with Min=2

### ISSUE THREAD

**Issue by thierrylio** [stsrki/Blazorise#1737]
It is not possible to enter a value starting with 1 like (10, 11, 100, ...) in a NumericEdit where the Min attribute set to 2.

```
<NumericEdit TValue="@(decimal?)"
             @bind-Value="Value"
             Min="2">
</NumericEdit>

@code {
    public decimal? Value { get; set; }
}
```

**Comment by stsrki** [comment]
@thierrylio I'm not sure what is the _right_ behavior here. For example when I try this code

```html
<!DOCTYPE html>
<html>
<body>

<h1>Display a Number Field</h1>

<form action="/action_page.php">
  <label for="quantity">Quantity (between 1 and 5):</label>
  <input type="number" id="quantity" name="quantity" min="2" max="5">
  <input type="submit">
</form>

</body>
</html>
```

and run it on https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_input_type_number I can enter `1` but I will get the error when I try to **submit**. So input is not limited from entering anything until submitting is done and validation is executed.

But the same code in Blazorise would not work because input validation is done on each keystroke, So for `Min=2` it makes sense to disable `1`. But, let's say we have `Min=10` as an example, When trying to enter `11` it would not work since first number `1` is less than `10`. And considering the w3schools example that is wrong.

So, I can try and do the same. Remove validation on each keystroke and then move that same validation to the `Validation` component. That could work, but it would not work when `NumericEdit` is used on its own.

- Will work `<Validation><NumericEdit Min="2"/></Validation>`
- Will not work `<NumericEdit Min="2"/>`

**Comment by thierrylio** [comment]
@stsrki thank you fo this. For my use case `Validation` is ok and I would not use `Min`.

The keystroke validation problem only appears for values ​​greater than 2. Negative, zero or 1.x `Min` values work well.
May be it would be possible to perform the validation on the Input lost focus event rather than on each keystroke !
