### ISSUE TITLE
DateEdit TValue should be used for setting Min and Max values as well

### ISSUE THREAD

**Issue by Smurf-IV** [stsrki/Blazorise#1746]
**Describe the bug**
    <DateEdit TValue="DateTimeOffset" Style="max-width: 200px" Date="@date" @onchange="OnDateChange" Min="@minDate" Max="@MaxDate"/>

**To Reproduce**
DateEdit TValue="DateTimeOffset"

Min and Max value types **HAVE** to be DateTime 

**Expected behavior**
Use TValue type

**Comment by stsrki** [comment]
I had problems with setting Min and Max as TValue because I couldn't make them **nullable**. And they must be null if they're not defined as parameters. Maybe nullable features in C# 9 would help, but for that, I would need to refactor the entire Blazorise codebase. 

So I can either put this on hold until I have more time to commit my self to do the refactoring or as a workaround make Min and Max object types, eg. `[Parameter] public object Min { get; set; }`

Any thoughts?

**Comment by Smurf-IV** [comment]
As this is a date edit control, then DateTime and DateTimeOffset can be null without being "nullable" (I think).
A compile time check for the types passed in (Much like it does for event OnChanged and edit-Value are both set.)

If you do go the object route, then put the comments into the code so that an observer of the code (Decompiler) can read those comments as well.
This control has to support .Net 3.1 LTS, so making things work for code bases beyond that will need different compile steps.

**Comment by stsrki** [comment]
It's not so easy. When you use a generic type, once initialized it will be set with its `default` type. That's how C# works. You can test it yourself with this simple code

```cs
DateTime d1 = default; // becomes 1.1.0001. 0:00:00
DateTime? d2 = default; // becomes null
```

This is because `DateTime` is a value type and it cannot be null unless you mark it as nullable. So if you define `DateEdit` component as 

```cshtml
<DateEdit TValue="DateTime" />
<DateEdit TValue="DateTime?" />
```

it will become

![image](https://user-images.githubusercontent.com/900302/105963122-e93b7380-6080-11eb-9447-f308a815556e.png)

![image](https://user-images.githubusercontent.com/900302/105963155-f193ae80-6080-11eb-86b0-91110efbd3b6.png)

Now, I **can pretend** for `default` value (`1.1.0001. 0:00:00`) to be null and then ignore it, but that is just wrong. The default value is still a valid value that can be used by someone.

**Comment by stsrki** [comment]
Making Min and Max as DateTimeOffset is the easiest and the best option I think. 

```cs
/// <summary>
/// The earliest date to accept.
/// </summary>
[Parameter] public DateTimeOffset? Min { get; set; }

/// <summary>
/// The latest date to accept.
/// </summary>
[Parameter] public DateTimeOffset? Max { get; set; }
```

It will allow for both DateTime and DateTimeOffset, including nullable types. And it will constrain us from setting the wrong value type.
