### ISSUE TITLE
DataGrid Check All - indeterminate state

### ISSUE THREAD

**Issue by stsrki** [stsrki/Blazorise#1777]
Might be a good feature to have an **indeterminate** state for **check-all** checkbox when not everything is selected.

![image](https://user-images.githubusercontent.com/900302/106486602-1be6d100-64b2-11eb-9aa3-96041597c560.png)

```cshtml
<Check Indeterminate="true"></Check>
```

@David-Moreira What do you think?

**Comment by David-Moreira** [comment]
I'm not sure what you mean?

Supporting 3 states instead of just on/off? 
So when there are items selected but not every single one of them. The checkbox displays an indeterminate state instead of the standard on/off? 

Does blazorise.check support that?

**Comment by stsrki** [comment]
I found this quick demonstration https://stackoverflow.com/a/48990131/833106

Yep, Check component supports indeterminate state.

**Comment by David-Moreira** [comment]
Yep makes total sense. 
It's visually more appealing and indicative.

However I don't think we need to expose a property telling if it's indeterminate to the developer, what do you think? Since we also don't expose if everything is selected or not.

I can pick this one up if you'd like, should be a quick addition since blazorise.check already supports it.

**Comment by stsrki** [comment]
No, we don't expose anything :). I just gave an example for you so you know that `Check` supports an indeterminate state (`<Check Indeterminate="true"></Check>`).

**Comment by David-Moreira** [comment]
Alright. Great. Seems good to me.
