### ISSUE TITLE
Blazorise.Animate Animate Delay and Duration properties not honoured

### ISSUE THREAD

**Issue by Sohra** [stsrki/Blazorise#1804]
**Describe the bug**
Regardless of what I set the Delay and Duration properties to, or even if I use DurationMilliseconds instead, it is ignored and the delay seems locked at 0, and the duration at 1000ms.  So for example, all of these render exactly the same way in my application:
```
<Animate Animation="Animations.Fade" Delay="TimeSpan.FromSeconds(5)" Duration="TimeSpan.FromSeconds(50)">Fade for 50 after 5</Animate>
<Animate Animation="Animations.Fade" Duration="TimeSpan.FromSeconds(50)">Fade for 50 immediately</Animate>
<Animate Animation="Animations.Fade" DurationMilliseconds="5000">Fade for 5 immediately</Animate>
<Animate Animation="Animations.Fade" Delay="TimeSpan.FromSeconds(5)" DurationMilliseconds="5000">Fade for 5 after 5</Animate>
```

I am trying 0.9.3-preview8 from the myget feed.  I also experience the same behaviour using the sample https://animateblazorsamplessvc.azurewebsites.net/testbed linked to from https://github.com/mikoskinen/Blazor.Animate.  No matter what I type into the Delay or Duration textboxes on this page and click Animate, nothing changes.  I'm using Edge Chromium and Google Chrome browsers and experiencing the same behaviour.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://animateblazorsamplessvc.azurewebsites.net/testbed
2. Type 5000 into the Delay textbox
3. Change the Duration from 1000 to 5000
4. Click Animate
5. See error - animates immediately over 1 second.

**Expected behaviour**
Five seconds after clicking the Animate button, the Counter slowly fades in over a further five seconds.

Source code for the aforementioned sample is at https://github.com/mikoskinen/Blazor.Animate/tree/master/samples/BlazorAnimate.Sample according to the old site.

**Additional context**
Of course the steps to reproduce and the repo I've specified here are not mine, they are for the sample listed at the original repo before it moved to Blazorise.  That means it is not running Blazorise.Animate 0.9.3-preview8 on .NET 5 as I am, it runs the older Blazor.Animate on .NET Core 3.1, but given I can reproduce exactly the same behaviour on this older version as the newer preview build, I'm just referencing this for convenience.  I was of two minds whether to raise the issue here or in the other repo, but since it is moving, here seemed the more appropriate place.

**Comment by Sohra** [comment]
I should add, I've spent an awful long time playing around on that test bed (trying to figure out the difference between Fade and FadeIn animations, hence the long durations!) and I would say perhaps 1% of the time, I have either the Delay or Duration setting honoured, but never both at the same time I don't think - and it's very rare that either works for me.

**Comment by stsrki** [comment]
@mikoskinen can you answer this question? You have more experience with the Animate library.

**Comment by mikoskinen** [comment]
Thank you for the question and sorry for the delay @Sohra. The underlying AOS.js adds some limits to these, this is from the library's documentation:

---
Duration and delay accept values from 50 to 3000, with step 50ms, it's because those are handled by css, and to not make css longer than it is already I implemented only a subset. I believe those should cover most cases.

If not, you can write simple CSS that will add another duration, for example:


```css
  body[data-aos-duration='4000'] [data-aos],
  [data-aos][data-aos][data-aos-duration='4000'] {
    transition-duration: 4000ms;
  }
```
This code will add 4000ms duration available for you to set on AOS elements, or to set as global duration while initializing AOS script.
Notice that double `[data-aos][data-aos]` - it's not a mistake, it is a trick, to make individual settings more important than global, without need to write ugly "!important" there :)

Example usage:
```html
  <div data-aos="fade-in" data-aos-duration="4000"></div>
```

---

I think you are bumping into these limitations. In the testbed, for example 2.5s delay and 3s duration works OK but any value over 3000 makes the library to use the default values defined by AOS: delay 0, duration 400ms.

The delay is for configuring the "The animation should run now, how much we delay it before actually running it". Duration is for configuring the "Ok the animation started, how long/slow will it run before it completes the animation has fully happened".

Hope this helps.

**Comment by Sohra** [comment]
Hi @mikoskinen ,

Thank you for the detailed reply, this is most helpful!  I'll take this information away and keep playing.
In the meantime I think this can be closed, thanks again.
