### ISSUE TITLE
NumericEdit Min="0" allows negative values

### ISSUE THREAD

**Issue by Jinjinov** [stsrki/Blazorise#1892]
**Describe the bug**

`<NumericEdit Min="0" Max="10"  />` allows the user to input `-999`

**Expected behavior**

When `Min >= 0` NumericEdit should not allow the input of `-` (minus character)

**Additional context**

I am searching for a temporary workaround and I am trying to set `<NumericEdit @ref="myEdit"  />` and `myEdit.SetValue("0");` but it does not work. Can I set `NumericEdit.Value` from code?

**Comment by Jimmys20** [comment]
Hello, the reason for this behavior is that the component can't distinguish the difference between passing Min="0"  and not setting the Min property at all. The component "thinks" the Min property has not been set because 0 is also the default value of not nullable numeric types ( e.g. `default(int) == 0` and `Min="0" == Min="default(int)"` ).

So a temporary work-around would be to use a nullable TValue e.g. `<NumericEdit TValue="int?" Min="0" />`. Now `default(int?) == null` but `Min="0" != Min="default(int?)"` so it will work fine.

Not sure if my explanation was clear. Also this is the line that's causing the issue: https://github.com/stsrki/Blazorise/blob/master/Source/Blazorise/JSRunner.cs#L60

**Comment by Jinjinov** [comment]
Thanks for the workaround!

If the problem is that `Min="0"` and `Max="0"` are treated as not setting the property at all, then one possible solution would be that `Min="int.MinValue"` and `Max="int.MaxValue"` should be treated as not setting the property instead.

**Comment by stsrki** [comment]
@Jimmys20 Thank you for this great explanation. You got it right. Just a note, there was some changed on 0.9.3 and the code is now https://github.com/stsrki/Blazorise/blob/dev093/Source/Blazorise/Components/NumericEdit/NumericEdit.razor.cs#L162

But the problem is still the same.

@Jinjinov  `Min="int.MinValue"` and `Max="int.MaxValue"` cannot be done because NumericEdit is a generic component and `TValue` cannot be initialized with `int.MinValue`. Until I found a better way you can try @Jimmys20 example with nullable values.

**Comment by Jimmys20** [comment]
Maybe initializing Min and Max properties inside SetParametersAsync method can fix this. Something like this:

```
public override async Task SetParametersAsync( ParameterView parameters )
{
    await base.SetParametersAsync( parameters );

    var (minFromType, maxFromType) = Converters.GetMinMaxValueOfType<TValue>();
    Min = parameters.TryGetValue<TValue>( nameof( Min ), out var minValue ) ? minValue : (TValue)minFromType;
    Max = parameters.TryGetValue<TValue>( nameof( Max ), out var maxValue ) ? maxValue : (TValue)maxFromType;
    ....
}
```

And then the IsEqual check in JSRunner.cs could be removed.

**Comment by stsrki** [comment]
That is what I'm currently trying to do. With your proposal change and also if I remove `value.CompareTo( defaultValue ) != 0`, it seems it works fine. I will do more testing before I submit the code.
