### ISSUE TITLE
DataGrid paging emit event 

### ISSUE THREAD

**Issue by andreatosato** [stsrki/Blazorise#1961]
When I load the grid, I display the data correctly but when I change the page I continually get the "change page" event.

**To Reproduce**
1. [Page](https://github.com/andreatosato/AwesomeBlazorise/blob/main/src/AwesomeBlazor/Pages/MoviesGrid.razor)
2. [Component](https://github.com/andreatosato/AwesomeBlazorise/blob/main/src/AwesomeBlazor/Components/Movies/AwMovieGrid.razor)

**Expected behavior**
Change page correctly

**You can download project and run, I use mock db with token hard-coded in repo**

P.S. I have also error with Chart (RADAR), changing to (PIE), with same data, it works properly.

**Comment by stsrki** [comment]
Your `PagedMovie.Page` is always the same and the problem is that with `CurrentPage="@PagedMovie.Page.Value"` you always reset the page number. Just add `PageChanged="(e) => PagedMovie.Page = e.Page"` parameter that will update `PagedMovie.Page` to be the real page number.

This behavior is the same as for all other Blazorise and Blazor components. If you define a parameter that can be changed dynamically you also must have a way to update it. This is called a two-way binding and you already saw it in the form of `@bind-Text="@text"`. This is practically the same, just that the API is a little different. We have the plans to make it better so it can also be written like `@bind-CurrentPage="@page"` or `@bind-Page="@page"`.

**Comment by andreatosato** [comment]
Great! 
Now works well!

**Comment by andreatosato** [comment]
Sorry, another understand feature:
I add this:
` <DataGridCommandColumn TItem="Movie" />`
Or I add this overload template: https://github.com/stsrki/Blazorise/blob/013ede7fa416147394a46b9010613c06b7b62729/Demos/Blazorise.Demo/Pages/Tests/DataGridPage.razor#L227-L246

**But I can't show Command Column.**

My sample: https://github.com/andreatosato/AwesomeBlazorise/blob/32b66592b418accfbce39415432554c3a70afbac/src/AwesomeBlazor/Components/Movies/AwMovieGrid.razor#L22

**Comment by stsrki** [comment]
You're missing `Editable="true"`.

**Comment by andreatosato** [comment]
I'm so stupid, I have comment it!
Sorry!
