### ISSUE TITLE
Italian translating errors

### ISSUE THREAD

**Issue by devrushnet** [stsrki/Blazorise#2014]
Hi, I have installed the last release of DataGrid Extension, in the navigation bar there are some translating errors, example :

 "Edit": "Modificare" -> "Modifica"
 "Clear Filter": "Filtro pulito" -> "Pulisci filtro"
"Last": "Scorso" -> "Ultimo"
"Next": "Il prossimo" -> "Successivo"
 "items per page": "oggetti per pagina" -> "Elementi per pagina"
"Create": "Creare" -> "Crea"

**Comment by Wolfenry** [comment]
In Spanish there are some mistakes too, and all the áéíóú are missing.
But you can modify it by the templates meanwhile.
eg:
```
    <LastPageButtonTemplate>
        Ultimo
    </LastPageButtonTemplate>
```

**Comment by stsrki** [comment]
Well considering I'm not speaking Italian or Spanish, I had to use google translate. And obviously, it is not the right choice. 

@devrushnet, @Wolfenry Can you guys write all the right translations? I will fix them for the next patch.

**Comment by devrushnet** [comment]
Hi @stsrki, 
I can help you.

**Comment by Wolfenry** [comment]
Glad to help! @stsrki 
Don't know where to post this properly. The actual bugs i see are the ones that figure on the Demo site too. So for now would be:
On `<LastPageButtonTemplate>` From Último to **Ultimo** (since the font doesn't recognize Ú, because Último is actually ok)
On `<NextPageButtonTemplate>` From Próximo to **Siguiente**
On `<ItemsPerPageTemplate>` From artículos por página to **filas por pagina** (página is ok too, i think english font won't recognize the ascii áéíóú)
And on the yellow clear filter button, from Filtro claro to **Limpiar filtros**


ASCII bug img:
![image](https://user-images.githubusercontent.com/33076177/110940381-93134e80-8315-11eb-8760-4a0fb5771ae5.png)

**Comment by stsrki** [comment]
For some reason, `es.json` switched to ANSI instead of UTF5. I will fix it.

**Comment by devrushnet** [comment]
Hi @stsrki ,

I have create a fork, can I start to modify the json italian resources ?

**Comment by stsrki** [comment]
Yes absolutely. Just make sure that the file encoding is UTF8 before submitting. Thanks!

**Comment by andreatosato** [comment]
@devrushnet I can help you to "italian translation"

[Successivo in this sample](https://github.com/devrushnet/Blazorise/blob/master/Source/Blazorise/Resources/Localization/Carousel/it.json#L4)

**Comment by devrushnet** [comment]
Hi @andreatosato,

How can we divide the tasks ?

**Comment by andreatosato** [comment]
Ok, sei in grado di fare un branch sul quale lavorare?
Altrimenti ne faccio uno sul mio e lavoriamo li.

La stai usando in produzione blazorise?

**Comment by stsrki** [comment]
Guys, I appreciate the effort. But can you please speak in English? 😅

**Comment by andreatosato** [comment]
Sorry, @devrushnet want to divide task.
I create new branch tomorrow

**Comment by devrushnet** [comment]
Hi @andreatosato ,

thank you for your patches.
right now, I'm studying all of Blazorise's controls to see if they can be put into production. For example I am using a grouping.
![image](https://user-images.githubusercontent.com/74462751/111064738-0358d600-84b6-11eb-822e-02988870c2d5.png).

**Comment by andreatosato** [comment]
Oh great!
I Need to add group in my example for blazorconf.it 😅

**Comment by stsrki** [comment]
@andreatosato Do you need any help with your _blazorconf.it_ preparations?

**Comment by andreatosato** [comment]
@stsrki I'm ready with sample.
I want to show aggregate grid, I need to work on it.
I have only 45 minutes.
I asked several developers what they are interested in seeing in the session.
Most would like to understand blazorise's state of evolution, strengths against other UI frameworks, and weaknesses (or those to be developed shortly).
For example Michele, who we find here in the conversation, mentions the grouping function of the grid.

For the demos I think I did a good job showing some images and some components.

**Comment by stsrki** [comment]
@andreatosato 

I think most of the people already have a rough idea about Blazorise. But just in case I can explain it more.

The main idea is to have an abstract API and Blazor syntax that is easily written and read. That's why I don't prefer any prefixes when naming components. (eg MatButton, RadzenButton). I just write a simple `Button`. It's easier for the eye in my opinion.

With Blazorise you're not bound to any CSS framework in particular. The same code should work in any situation with slight modification in the project configuration. Given that not a lot of custom CSS was done you can just switch from Bootstrap to AntDesign for example.

Now, obviously, all this abstraction comes at a cost. Some very specific features of one particular framework can be hard to implement. But even that is not the problem. Like a lot of times in the past, I have made some features to work on all supported providers. So while not easy, almost everything can be done eventually, Which is slowly closing the gap of what is left to do.

And new features will always come. It's just a matter of time. Even the Datagrid grouping.
