### ISSUE TITLE
FigureImage shows different result (than the docs) for image not found

### ISSUE THREAD

**Issue by sturlath** [stsrki/Blazorise#2236]
That is at least what I thought after looking at "image not found result" in the [docs](https://blazorise.com/docs/components/figure/)

If I add the following code to my page to show an image

```xml
<Figure Size="FigureSize.Is256x256">
    <FigureImage Source="assets/images/empty/256x256.png" AlternateText="256x256" />
    <FigureCaption>A caption for the above image.</FigureCaption>
</Figure>
```

I get this
![image](https://user-images.githubusercontent.com/2386572/115927439-f693ae80-a473-11eb-9313-ce810456d205.png)

instead of **my** expected result of (a sized box of 256x256 with that text centred)

![image](https://user-images.githubusercontent.com/2386572/115927496-08755180-a474-11eb-9807-eb236b69ad6e.png)

Is this just a CSS styling "issue" at my end or is something broken there?

**Comment by stsrki** [comment]
Can you confirm you have the actual image in your wwwroot folder under `assets/images/empty/256x256.png`?

**Comment by sturlath** [comment]
No such image at my end
![image](https://user-images.githubusercontent.com/2386572/115930459-02ce3a80-a479-11eb-9278-a25079bcd170.png)

I´m using 0.9.3-preview6

**Comment by stsrki** [comment]
You will need to download it into your wwwroot folder.

**Comment by sturlath** [comment]
Ok I manually downloaded the image and placed it under wwwroot/assets/images/empty and if I have Source pointing to it it is shown **but** If I point to some none-existing image I get the broken-image as shown in my first post.

I think I´m misunderstanding how this all works, I thought that if Source didn't contain valid image a empty image would be shown, not just alt text. 

Now that I know how this works I can work with it, thanks

**Comment by sturlath** [comment]
I also notice that there are empty images for all but 512x512

**Comment by stsrki** [comment]
Yeah, I think you misunderstood how figure image is working. It will not show any default or empty image if it doesn't exist. As in all other components its purpose is to create the right HTML tags and classnames. eg `<img src="some-image-path" class="figure-img img-fluid" alt="some text">`. Since every provider is different the structure can vary, and that is why Blazorise is here. So you don't need to worry about those things.

So, I mentioned before. You must handle the images on your project side. There is no way around it.
