### ISSUE TITLE
Control over Edit and New command on DataGrid

### ISSUE THREAD

**Issue by elephs** [stsrki/Blazorise#234]
I have now a problem of DataGrid. I would like to have an editable field at "New" but keep it readonly at "Edit".
Both options Readonly and AllowEdit have the same behavier for "Edit" and "New".
And currently it seems no workaround.

Thank you for your help.

**Comment by stsrki** [comment]
Hm, interesting problem. Maybe I could add a callback on edit mode switch that can be used to set the read-only state. I will need to investigate more.

**Comment by robalexclark** [comment]
I need the opposite functionality - allow "edit" but not "new". Ideally the "New" button should not appear. I can see that users could need to choose between all three e.g. new and delete but not edit, or new and edit but not delete etc.

Could we configure this through the <DataGridCommandColumn>, so that if a CommandTemplate type is not configured then it does not appear?

**Comment by stsrki** [comment]
If you want to disable New button you can just leave an empty NewCommandTemplate.

```cshtml
<NewCommandTemplate>
    // nothing here
</NewCommandTemplate>
```

I agree there needs to be a better way to handle the editing-modes.

**Comment by declan-m** [comment]
You could add two variables `CanEdit` `CanEditNew` as booleans and handle accordingly.

**Comment by stsrki** [comment]
Features are added with the #383
