### ISSUE TITLE
Dropdown going out of bounds

### ISSUE THREAD

**Issue by Kirides** [stsrki/Blazorise#244]
happens with every type of theme (Bootstrap, Material, etc.)
![Image](https://puu.sh/Ee4uh.png)

expected: dropdown that is all the way at the bottom pops up pointing up
real: dropdown that is all the way at the bottom pops up pointing down, going out of bounds

**Comment by stsrki** [comment]
I've tried dropdown for every CSS framework on their own documentation page and only Bootstrap dynamically moves menu based on the visible bounds. As it's stated in their documentation it's because they're using a [Popper.js](https://popper.js.org/) library.

- [Bootstrap](https://getbootstrap.com/docs/4.3/components/dropdowns/)
- [Bulma](https://bulma.io/documentation/components/dropdown/)
- [eFrolic](https://efrolicss.com/dropdown)

I want to limit third-party dependencies to a minimum so I will investigate more what can be done.

**Comment by stsrki** [comment]
Added `data-toggle="dropdown"` to toggle component. This will automatically fix bug for bootstrap implementation since it comes with `popper.js` by default. For other providers a developer need to add this implementation manually.
