### ISSUE TITLE
SelectEdit doesn't update binded complex type

### ISSUE THREAD

**Issue by hybrid2102** [stsrki/Blazorise#292]
SelectEdit doesn't update binded complex type (works with simple int, string, etc)

**Comment by stsrki** [comment]
`<SelectList>` is used for complex types https://blazorise.com/docs/extensions/selectlist/

**Comment by hybrid2102** [comment]
Thank you very much. I may suggest to improve documentation, explaining differences between  SelectEdit, SelectList and Dropdown which are, in my opinion, not so obvious.

**Comment by stsrki** [comment]
Noted, I will make changes to the documentation. tnx

**Comment by hybrid2102** [comment]
> `<SelectList>` is used for complex types https://blazorise.com/docs/extensions/selectlist/

I can't get it working. Seems that SelectedValue value and SelectedValueChanged handler parameter, are filled with my binded object's .ToString()
I'm probably missing something!

`                <SelectList Data="@allBrands" TextField="@((item)=>item.Name)" ValueField="@((item)=>item)" SelectedValue="@SelectedBrand" SelectedValueChanged="@MyListValueChangedHandler" />


    void MyListValueChangedHandler( object newValue )
    {
        SelectedBrand = (VehicleBrand)newValue; // exception! newValue is of type string
        StateHasChanged();
    }

`

**Comment by stsrki** [comment]
Can you post full use-case example?

**Comment by hybrid2102** [comment]
https://github.com/hybrid2102/BlazorizeLab

**Comment by stsrki** [comment]
Hi @hybrid2102 

Sorry for the long response. Anyways I tried your example and I'm afraid it wont be possible. `SelectList` is using html `select` and `option` tags internally and the problem is that `option` can only use string or basic data-types for it's `value` attribute.

When you use `VehicleBrand` for value it will convert it to string by calling `.ToString()` and that will just return the object name.

To make it work you have to return the actual field from your `VehicleBrand` to be used by `SelectList`:

```cshtml
<SelectList Data="@allBrands"
            TextField="@((item)=>item.Name)"
            ValueField="@((item)=>item.Id)"
            SelectedValue="@SelectedBrand"
            SelectedValueChanged="@MyListValueChangedHandler" />
```
