### ISSUE TITLE
Validation in datagrid

### ISSUE THREAD

**Issue by robalexclark** [stsrki/Blazorise#306]
Is it possible to use a <ValidationSummary> component in conjunction with inline datagrid editing? Or, do we need to manually provide our own (for example manually validate on the RowSaving event)?

**Comment by stsrki** [comment]
Hi @robalexclark 

Validation in datagrid is currently not supported in full. You can try to go with combination of `<EditTemplate>` and `<Validation>`, and `RowSaving` event.

1. For example you can try to add `<Validation>` into every column along with the `<EditTemplate>`. This way you will cover the individual inputs.

```cshtml
<DataGridColumn TItem="Employee" Field="@nameof( Employee.Salary )" Caption="Salary" AllowEdit="true">
    <DisplayTemplate>
        @($"{( context as Employee )?.Salary} €")
    </DisplayTemplate>
    <EditTemplate>
        <Validation Validator="@MyCustomValidatorHandler">
            <NumericEdit TValue="decimal" Value="@((decimal)( ( (CellEditContext)context ).CellValue ))" ValueChanged="@(v => ( (CellEditContext)context ).CellValue = v)" />
        </Validation>
    </EditTemplate>
</DataGridColumn>
```

2. You can try a `RowSaving` and in that case you can validate all fields at once instead of individually.

**Comment by CJMarinacci** [comment]
I tried this approach, and it appears to work at first. Unfortunately, every time the EditTemplate is initialized, the Validation is added to the validations list in the parent Validations object, and it is never removed, so you get a bunch of "ghost" validations that can cause issues.

**Comment by stsrki** [comment]
That's strange. It should not behave like that. I guess it's because it's placed inside of rendering fragment it will reinitialize new component on every refresh.
