### ISSUE TITLE
Larg data in lineChart

### ISSUE THREAD

**Issue by Saeidasadi32** [stsrki/Blazorise#338]
I try to use linechart with more then 200 record and I need to not show label in bottom , but i need to show other data when mouse move over line.
Is it possible?

**Comment by stsrki** [comment]
Hi @Saeidasadi32 

I'm not a chart expert but a quick google search lead me to this solution: https://stackoverflow.com/a/23424876/833106

When we apply it to Blazorise it should be like this:

```
<LineChart @ref="lineChart" TItem="double" OptionsJsonString="@("{\"scales\": {\"xAxes\": [{\"ticks\": {\"display\": false}}]}}")" />
```

Notice the `OptionsJsonString` attribute. It is actually used to manually apply json settings since the .NET Core JSON serializer is not that good unfortunately. So for now you can use `OptionsJsonString` instead of `Options`, just keep in mind it will be removed eventually once the Blazor team fixes the serializer.
