### ISSUE TITLE
Snackbar Customization for Error/Success/Info/Warning

### ISSUE THREAD

**Issue by WillianGruber** [stsrki/Blazorise#358]
**Describe the solution you'd like**
Implement a way to show the Snackbar with colors, background colors and icons for Error/Success/Info/Warning.

**Comment by WillianGruber** [comment]
Maybe an option to enable/disable countdown bar displaying when the snackbar will close. Needs to be done partly in jsinterop in order to not flood server with requests.

**Comment by stsrki** [comment]
Not sure about the counter. Colors are OK.

**Comment by stsrki** [comment]
One thing bothers me. What part of snackbar actually need to have variant colors?

Is it a background or text color? For example if we change background color than the text colors sometimes cannot be read because the contrast is too similar.

So it leads to conclussion that both of them needs to be confugurable for every possible color variant. eg:

```css
$primary: ( background: #808080, text: #ffffff ) !default;
$secondary: ( background: #323232, text: #ffd800 ) !default;
// etc
```

Probably the same for action button.

**Comment by WillianGruber** [comment]
Couldn't find the example I had before, sorry. But you are right about the colors. Also, I thought that it would be nice to have an icon in the left of the message if possible.

**Comment by stsrki** [comment]
@WillianGruber I have added support for colors on snackbar.

Background color calculation is controlled by the `ThemeSnackbarOptions.VariantBackgroundColorLevel`. Text and button color are calculated as contrast(from background) so that for each possible color combination it can be read without difficulty.

Hope that is OK.

**Comment by WillianGruber** [comment]
Thanks @stsrki , will test it when I finish my sprint!
By the way, is there a changelog for 0.9 so far? It would be way easier to know if there is a new attribute in Theme, for example

**Comment by stsrki** [comment]
I don't plan to write release notes until I finish v0.9. In the meantime you look at the project board where you can find every task so far. https://github.com/stsrki/Blazorise/projects/8

**Comment by WillianGruber** [comment]
Sure!
