### ISSUE TITLE
Resizeable columns (drag-to-resize) in DataGrid.

### ISSUE THREAD

**Issue by stsrki** [stsrki/Blazorise#393]

**Comment by Jinjinov** [comment]
I really need this feature, but I can't find much about resizing in Blazor - I only found this:

https://github.com/dotnet/aspnetcore/issues/14132#issuecomment-533069194

This comment is 1 year old... is there anything new in Blazor since then?

Can I help somehow? (right now I am learning Blazor, but I have 18 years of experience with C#, WinForms, WPF)

**Comment by stsrki** [comment]
It will take a while until I commit to this feature.. If you could do it and create a PR I would be glad to help.

**Comment by Jinjinov** [comment]
After some googling it seems like there is no way to do this in pure C# (or perhaps I don't know what to search for).

It seems like JS interop is the only way to do this - but my knowledge of JavaScript is very limited...

I will take a look, but I can't promise anything...

**Comment by Jinjinov** [comment]
I took a quick look and this is what I found out:

You can use CSS resize property (https://www.w3schools.com/cssref/css3_pr_resize.asp) but it only works with a resize handler in the bottom right corner and it can't be changed.

There are a few alternatives, but they require additional JavaScript:

https://stackoverflow.com/questions/12194469/best-way-to-do-a-split-pane-in-html
https://stackoverflow.com/questions/46931103/making-a-dragbar-to-resize-divs-inside-css-grids

Or, you can use JavaScript libraries:

https://split.js.org/ 
https://jqueryui.com/resizable/
https://github.com/RickStrahl/jquery-resizable

I didn't find a "splitter" component in Bootstrap, but I found one in Metro:

https://metroui.org.ua/splitter.html

Here are some library comparisons:

https://www.w3tweaks.com/8-css-re-sizable-panes.html
https://www.digitaldesignjournal.com/jquery-resizable-div/

I don't like to include libraries, because everything becomes bloated, so I would choose plain JS from the stackoverflow.

What do you think?

**Comment by stsrki** [comment]
I tend to use vanilla JS as much as possible so I would choose that path in this case.

From the links provided splitting is not that complicated, I have even done it in some of my projects. But it might be difficult to add it to DataGrid. or it might be easy. We'll both know once the work starts :)

**Comment by Jinjinov** [comment]
I agree - the use vanilla JavaScript is optimal.

I have very little experience with JavaScript, but I will try to combine this example with Blazor: https://htmldom.dev/resize-columns-of-a-table/ because it has the cleanest code of all examples and because https://htmldom.dev/ seems like a nice page.

I don't know how much time I will have to work on this... if I have any success, I should fork the dev092 and make my own branch, right?

**Comment by stsrki** [comment]
I like https://htmldom.dev/, I wonder how I didn't found it sooner :)

Yes, you should fork Blazorise and then checkout and create new feature branch from dev092
