### ISSUE TITLE
NavMenu is not displayed and does not go to /counter

### ISSUE THREAD

**Issue by Neoplayer** [stsrki/Blazorise#432]
NavMenu is not displayed and for some reason does not go to /counter but api works correctly

https://github.com/Neoplayer/Blazzzor

![image](https://user-images.githubusercontent.com/17293976/70392819-b3f34280-19f4-11ea-9767-42d30f75e5e0.png)
![image](https://user-images.githubusercontent.com/17293976/70392822-bf466e00-19f4-11ea-9419-b5a005237ec6.png)

**Comment by nmiddelmann** [comment]
Hi @Neoplayer , can you give me some hint? I have the same issue

**Comment by EternalWind** [comment]
> Hi @Neoplayer , can you give me some hint? I have the same issue

@nmiddelmann I just ran into this issue myself. Turns out it is because I am pasting the reference to bootstrap's css after site.css like below.

`<link href="css/site.css" rel="stylesheet" />
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">`

According to [CSS's precedence rules](https://stackoverflow.com/questions/25105736/what-is-the-order-of-precedence-for-css), the one comes later takes precedence over the earlier one.

After I swapped them, it works correctly. Maybe this is your case as well.

**Comment by markiemarkus** [comment]
> Hi @Neoplayer , can you give me some hint? I have the same issue

I had the same issue in a blank Blazor Server project.
The solution was to remove the following line from the _Host.cshtml file

    @*<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>*@

**Comment by Rambalac** [comment]
Indeed, some bug with stylesheets prevents NavBar display in desktop view.

Commenting that script line did not help for me, I had to comment
`<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">`

**Comment by sunnamed434** [comment]
> In your _Layout.cshtml or index.html
> 
> change the order of this code
> 
> ```
> <link href="Demo.styles.css" rel="stylesheet" />
> <link rel="stylesheet" href="css/bootstrap/bootstrap.min.css" />
> ```
> 
> to the following
> 
> ```
> <link rel="stylesheet" href="css/bootstrap/bootstrap.min.css" />
> <link href="Demo.styles.css" rel="stylesheet" />
> ```

fixed it by moving it as lower as possible <link href="Demo.styles.css" rel="stylesheet" />
