### ISSUE TITLE
Button text always in upper case

### ISSUE THREAD

**Issue by WillianGruber** [stsrki/Blazorise#446]
**Describe the bug**
Hi, using a simple button like
`<Button Color="Color.Primary">Primary</Button>`
renders a the text as uppercase:
![image](https://user-images.githubusercontent.com/56033692/71107821-9e261000-21a0-11ea-9c31-67fb181964ff.png)
Am I missing something obvious?

**Comment by stsrki** [comment]
[daemonite](http://daemonite.github.io/material/docs/4.1/components/buttons/) have a special rule for buttons to always be uppercase. I also checked the official [material](https://material.io/components/buttons/#) documentation. It seems that is by design.

![image](https://user-images.githubusercontent.com/900302/71122192-4d360c00-21e0-11ea-87da-a4cf8b08d099.png)

You gave me an idea now. I think I can abstract this through Blazorise so it can be controlled. Something like `enum Casing`:

- `Normal`
- `Uppercase`
- `Lowercase`
- `TitleCase` // only the first letter is upper-cased

**Comment by WillianGruber** [comment]
Thank you! I thought I was going crazy and missed something

**Comment by stsrki** [comment]
Added `Casing` attribute to handle characters casing of an element.

**Comment by WillianGruber** [comment]
Nice! Did you keep the uppercase as default? Or changed to "raw" as the text is passed?

**Comment by stsrki** [comment]
By default `Casing `is set to `Normal`. Which means nothing will be changed.
