### ISSUE TITLE
NumericEdit

### ISSUE THREAD

**Issue by carlosast** [stsrki/Blazorise#50]
How to bind with nullable decimal properties?
TextEdit supports string only.
Is there no equivalent DateEdit control for numbers?

**Comment by stsrki** [comment]
There is not for now. I'm planning to do it maybe in the next release(0.6.1) as soon as I decide what is the best route to go. There are two options:

1. Create NumericEdit with all the possible number formatting, decimal places. integers etc.
2. Convert TextEdit to a generic component will all of the above

For now I prefer the first option because it is cleaner while the second option could be a little messy.
What are your thoughts?

**Comment by carlosast** [comment]
I believe the first option is the best. And have the ability to work with nulls as well. The Microsoft InputNumber control does not accept nulls. There you have to create an additional property just to use the control.

**Comment by stsrki** [comment]
I have created NumericEdit because there were some limitations with generic components when I tried to expand TextEdit. Now I'm testing it and will release soon. Null values will also be supported.

**Comment by carlosast** [comment]
I've done an update on the Blazorize packages but NumericEdit is not showing up
Thank you very much.

**Comment by stsrki** [comment]
I have just create new Blazor project using the latest Blazorise 0.6.1 and I can use `NumericEdit` component just fine. Maybe something has left catched after the update on your side. Try just to close/open your page component and/or visual studio.

**Comment by brettwinters** [comment]
Is this working?

I just tried this: 

```html
<NumericEdit TValue="decimal?" Value="@DefaultValue" ValueChanged="@ValueChanged" />
```

But got this : 

![image](https://user-images.githubusercontent.com/26474006/60638055-13966200-9e47-11e9-9c71-4e3c0686cdee.png)
