### ISSUE TITLE
[Question] ValueExpression

### ISSUE THREAD

**Issue by WillianGruber** [stsrki/Blazorise#565]
Hi all,
I see in some components the attributes Value, ValueChanged and ValueExpression.
What is the use of ValueExpression?

**Comment by stsrki** [comment]
It's a _dirty_ little secret in Blazor framework. Whenever you have `Value` and `ValueChanged` on any component Blazor will internally also create expression parameter. The good part is you can also create it yourself so that Blazor can use that one instead. It's used internally for two-way bindings. I'm In Blazorise I use it for data-annotated validations.

**Comment by WillianGruber** [comment]
Any example of use?

**Comment by stsrki** [comment]
You don't need to use it. Blazor is taking care of that. I just had to include `ValueExpression` into Blazorise so I could implement data-annotated validations.

**Comment by WillianGruber** [comment]
Ah, ok!
