### ISSUE TITLE
DataGridColumn visibility

### ISSUE THREAD

**Issue by mkchx** [stsrki/Blazorise#599]
**Is your feature request related to a problem? Please describe.**
I'm trying to control the visibility of DataGridDateColumn, DataGridColumn's etc.. based on a filter (checkboxes) I've made.

**Describe the solution you'd like**
I think the most suitable way would be to pass the Visibility attribute with the desired value
and once the boolean changes, from our side we would call StateHasChanged() to take effect.

### Additional context
<DataGridColumn Visibility="@(columnFilter.NumberColumn ? Blazorise.Visibility.Default : Blazorise.Visibility.Never)" ... />

**Comment by stsrki** [comment]
Seems like a good feature to have. Thank you for posting.

**Comment by geersjake** [comment]
Bumping this for visibility. Being able to set a column's visibility to false would allow the work around mentioned in (331)[https://github.com/stsrki/Blazorise/issues/331] to actually work when dealing with databases and foreign keys. 

Currently, the workout requires two columns, the id field (still necessary for db operations) and the display field. Since you need the id field but cant hide it, it makes for ugly data grids.

**Comment by stsrki** [comment]
I forgot about this ticket. Anyways I have already done it with #605

The actual property will be called `Displayable` and will control visibility of column in display mode only.

**Comment by geersjake** [comment]
Cool. Thank you!

**Comment by stsrki** [comment]
I think this can be closed. If you need more help please reopen. tnx
