### ISSUE TITLE
Memo cursor jumps to end when enclosed in a field and Text is bound

### ISSUE THREAD

**Issue by roji** [stsrki/Blazorise#655]
With the following page below (used on Blazor server):
1. Type some text into the first memo field
2. Click somewhere in the middle of the text just typed
3. Hit a single key to insert a new character

Result: the cursor jumps to the end of the line.

Curiously, if the <MemoEdit> isn't enclosed in a field, this does not occur for me. If its Text attribute isn't bound, this doesn't happen either.

```
@page "/foo"

<h1>Inside field with binding</h1>

<Field>
    <FieldLabel>Notizen:</FieldLabel>
    <FieldBody>
        <MemoEdit Rows="5" @bind-Text="@SomeBar"/>
    </FieldBody>
</Field>

<h1>Inside field without binding</h1>

<Field>
    <FieldLabel>Notizen:</FieldLabel>
    <FieldBody>
        <MemoEdit Rows="5" />
    </FieldBody>
</Field>

<h1>Outside field with binding</h1>

<MemoEdit Rows="5" @bind-Text="@SomeBar"/>

@code
{
    string SomeBar = "";
}
```

Using Blazorise.Bootstrap 0.8.8.3

**Comment by stsrki** [comment]
Hi @roji, I have investigated this issue and I think it's the same problem as this one: https://github.com/dotnet/aspnetcore/issues/20067

Both Field and FieldBody have cascading value that is tracked by the MemoEdit. Whenever MemoEdit changes it's state with `@bind` it will automatically trigger re-render for that part of rendering tree. After it's done the browser will by default set cursor to the last place in the input.

I will need more time to investigate and see if this can actually be fixed or is it by design(on Blazor side) so I'm putting it on backlog for now as I still need to finish current 0.9 version.

**Comment by roji** [comment]
No problem - I'm working around it by not enclosing the memo in a field. Thanks for taking the time to look and in general for a great component library!

**Comment by Stefan6440** [comment]
Just FYI. I ran into exactly the same issue a few days ago. 
And my workarround was the same as yours:  skipped the Field-structure (I used Row and Column instead).

**Comment by stsrki** [comment]
Hi @roji @Stefan6440 this is the same issue as in #733 

Please look at the comment https://github.com/stsrki/Blazorise/issues/733#issuecomment-632912348

When you got the chance please test again with latest version. tnx

**Comment by roji** [comment]
FYI am no longer concentrating on that project (plus the workaround of not using memo inside a field is fine), hopefully @Stefan6440 can confirm.

**Comment by Stefan6440** [comment]
I can confirm the work arround is still working fine. I just tested with version 0.9.3, and works fine.
