### ISSUE TITLE
[BUG-Datagrid] OnRowInserted not executed when UseInternalEditing=True

### ISSUE THREAD

**Issue by CPlusPlus17** [stsrki/Blazorise#673]
**Describe the bug**
OnRowInserted not executed when UseInternalEditing=True.
OnRowUpdated works with both conditions.

**To Reproduce**
1. Use provided Class and Template

**Expected behavior**
Should also be called when UseInternalEditing=False.

**Additional context**
Tested v0.8 and v0.9 preview.

```cshtml
@page "/VersionShow"
@inject HttpClient Http
@using Version = Cfg.Shared.Entities.Version;
<h1>Versions</h1>


<DataGrid TItem="Version"
          Data="@versionList" Editable="true" EditMode="@editMode" Filterable="true" RowInserted="@OnRowInserted" RowUpdated="@OnRowUpdated">
    <DataGridCommandColumn TItem="Version">
        <ClearFilterCommandTemplate>
            <Button Color="Color.Primary" Clicked="@context.Clicked">Clear filter</Button>
        </ClearFilterCommandTemplate>
        <NewCommandTemplate>
            <Button Color="Color.Success" Clicked="@context.Clicked">New</Button>
        </NewCommandTemplate>
        <EditCommandTemplate>
            <Button Color="Color.Warning" Clicked="@context.Clicked">Edit</Button>
        </EditCommandTemplate>
        <DeleteCommandTemplate>
            <Button Color="Color.Danger" Clicked="@context.Clicked">Delete</Button>
        </DeleteCommandTemplate>
        <SaveCommandTemplate>
            <Button Color="Color.Success" Clicked="@context.Clicked">Save</Button>
        </SaveCommandTemplate>
        <CancelCommandTemplate>
            <Button Color="Color.Secondary" Clicked="@context.Clicked">Cancel</Button>
        </CancelCommandTemplate>
    </DataGridCommandColumn>
    <DataGridColumn TItem="Version" Field="@nameof(Version.Id)" Caption="#" Sortable="false" />
    <DataGridColumn TItem="Version" Field="@nameof(Version.Name)" Editable="true" Caption="Name" />
</DataGrid>


@code {
    Version[] versionList;
    DataGridEditMode editMode = DataGridEditMode.Inline;

    protected override async Task OnInitializedAsync()
    {
        versionList = await Http.GetJsonAsync<Version[]>("Version");
    }

    async Task OnRowInserted(SavedRowItem<Version, Dictionary<string, object>> e)
    {
        System.Diagnostics.Debug.WriteLine("called ins");
    }

    async Task OnRowUpdated(SavedRowItem<Version, Dictionary<string, object>> e)
    {
        System.Diagnostics.Debug.WriteLine("called edi");
    }
}

```

```cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text;

namespace Cfg.Shared.Entities
{
    public class Version
    {
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
    }
}   
```

**Comment by CPlusPlus17** [comment]
After studying the code more, I think data.Remove causes an exception? I can't find anyway currently to validate this. Should this be handles blazor WASM? Some exceptions are printed to the chrome console, in this case I see nothing.

```cs
                    if ( UseInternalEditing )
                    {
                        if ( data.Contains( item ) )
                            data.Remove( item );
                    }
```

**Comment by stsrki** [comment]
Might be the problem with `versionList` being null. 

Try to move `versionList = await Http.GetJsonAsync<Version[]>("Version");` into `OnAfterRenderAsync` and load only when `firstRender` is true.

If that doesn't help try to initialize versionList  with an empty array. Just to make sure it's not null.

**Comment by stsrki** [comment]
Hi, any change on this? Did you managed to find the solution?

**Comment by CPlusPlus17** [comment]
Hello

Your workaround did not help, but your tip that he have problems with the null array.
So I switch it to a List:

```cs
 List<Property> propertyListOverSys = new List<Property>();
```

This fixed the problem.

**Comment by CheetahChrome** [comment]
Doesn't the save button need to *also* need to have `PreventDefaultOnSubmit` such as

     <Button Color="Color.Success" PreventDefaultOnSubmit Clicked="@context.Clicked">Save</Button>


... or am I misunderstanding something?

**Comment by David-Moreira** [comment]
@CheetahChrome can you elaborate? If you're having any issues, please open a new one with detailed info.

**Comment by CheetahChrome** [comment]
I'm not having an issue per-se, but in researching examples, a StackOverflow  question ([Update Method RowInserted Not Called On Submit for Blazorise DataGrid - Stack Overflow](https://stackoverflow.com/questions/67010085/update-method-rowinserted-not-called-on-submit-for-blazorise-datagrid)) gave the advice to add `PreventDefaultOnSubmit`. 

Since the OP on this question stated that his problems were not resolved by advice taken...I wondered if `PreventDefaultOnSubmit` might be related to his issue....

**Comment by David-Moreira** [comment]
I think it was actually solved. He did say :
> This fixed the problem.

My guess is that OP was having trouble with Datagrid's `UseInternalEditing` not calling/correctly executing certain methods, in particular, the `RowInserted`, `RowRemoved`.

Since apparently OP was not binding a Collection which is a requirement for the Datagrid's internal editing to be able to actually insert/remove items. But again I'm not sure...

Could also be what you're saying.. But as far as I know you would not need `PreventDefaultOnSubmit` as properly calling `context.Clicked` should trigger the datagrid's events correctly...

But issue is super old by now... so. :)
Eitherway thank you for your attention. If any actual issue related to this happens, please let us know so we can help. :)
