### ISSUE TITLE
.b-body-layout is not working Bulma 

### ISSUE THREAD

**Issue by stsrki** [stsrki/Blazorise#722]
'.b-body-layout' is messing with Bulma layout content. It needs to be disabled.

**Comment by MitchellNZ** [comment]
@stsrki I did some investigating into this issue.

It appears that `bulma.css` is applying `overflow-x: hidden` to the root `html` element (as you can see [here](https://github.com/jgthms/bulma/blob/0.8.2/css/bulma.css#L314)). 
This is what is causing an issue, because it ends up having `overflow-x: hidden` on both `html` and `body` elements.

I did some testing and found 2 possible solutions:
1. The fix we did for `.b-body-layout` can actually be applied to the root `html` element for all providers like `bulma` is doing (instead of the `body` element) and it will still work correctly.
2. Do what you are suggesting and disable `.b-body-layout` for Bulma, but leave it for the other providers.

I will leave the decision to you, just thought I would share my findings.
Hope this helps!

**Comment by stsrki** [comment]
I would remove `b-body-layout` from Blazorise css and move it only to providers that needs it. In this case every other except for Bulma.

If you have time it would be great if you could do it.

**Comment by MitchellNZ** [comment]
Sure thing, should be free in a couple of hours.
Will do it then.
