### ISSUE TITLE
Bug in Radio component

### ISSUE THREAD

**Issue by soltrac** [stsrki/Blazorise#783]
**Describe the bug**
CheckedChanged is not working correctly

**To Reproduce**
Create a RadioGroup with 2 elements with CheckedChanged event and default, first element checked. If you click the second element, CheckedChanged is fired, but if you return to the first one again, CheckedChanged is not fired. 

**Expected behavior**
CheckedChanged should fire always

**Comment by stsrki** [comment]
Hi, can you post an example? Tnx

**Comment by soltrac** [comment]
Sure,

`<RadioGroup TValue="int" CheckedValueChanged="SaleSpecialChanged" Name="Test">
  <Radio TValue="int" Value="@(0)">0</Radio>
  <Radio TValue="int" Value="@(1)">1</Radio>
</RadioGroup>`

Above code is working, SaleSpecialChanged is called every time I change the radio.

But this:

`<RadioGroup TValue="int" CheckedValue="SelectedIndexRadio" CheckedValueChanged="SaleSpecialChanged" Name="Test">
  <Radio TValue="int" Value="@(0)">0</Radio>
  <Radio TValue="int" Value="@(1)">1</Radio>
</RadioGroup>`

If I add CheckedValue, it only works when I check the second radio, but if I check the first one, SaleSpecialChanged is not fired

**Comment by stsrki** [comment]
What is the content of `SaleSpecialChanged` method?

**Comment by soltrac** [comment]
It does not matter, If I set it empty, it is not working either.

**Comment by stsrki** [comment]
That is your problem. When you don't set CheckedValue then Blazorise will use whatever is the internal value of current Radio.

But when you set CheckedValue than on each refresh it will use that value to match with internals. Now your problem is that you have left it always on default. You are using manual two-way binding which means you must update your SelectedIndexRadio.

```cshtml
<RadioGroup TValue="int" CheckedValue="SelectedIndexRadio" CheckedValueChanged="SaleSpecialChanged" Name="Test">
    <Radio TValue="int" Value="@(0)">0</Radio>
    <Radio TValue="int" Value="@(1)">1</Radio>
</RadioGroup>

@code{
    int SelectedIndexRadio;

    void SaleSpecialChanged( int selected )
    {
        SelectedIndexRadio = selected;
        Console.WriteLine( selected );
    }
}
```

This is actually how Blazor work in general, either you use automatic two-way binding or manual

- Auto: `@bind-CheckedValue="@someValue"`
- Manual: `CheckedValue` with `CheckedValueChanged` but must update value always

**Comment by soltrac** [comment]
Got it, I close this then. Sorry for the inconvenience

**Comment by stsrki** [comment]
No problem, glad I can help.
