### ISSUE TITLE
FileEdit ChildContent is rendered twice

### ISSUE THREAD

**Issue by hesuruio** [stsrki/Blazorise#840]
The ChildContent is rendered twice.

```html
<FileEdit Filter=".tsv, .txt" Changed="@FileUploadChanged" Written="@FileUploadOnWritten" Multiple="false" Progressed="@FileUploadOnProgressed" >
@UploadedFileName
</FileEdit>
```

![image](https://user-images.githubusercontent.com/13237805/80516458-682d3f80-897b-11ea-9349-a8bd7bceac51.png)

**Comment by stsrki** [comment]
That is the expected behavior. `FileEdit `is using native input **element** with `type="file"` meaning when you select the file it's filename will be shown inside of an input. With `@UploadedFileName` you have told Blazor to render it inside of `FileEdit` **component**. This is allowed so you can place additional content inside/next to the input, in case you need it. And in this case it's just a duplicate.

**Comment by cristian-recoseanu** [comment]
Hi @stsrki 
Thanks for the reply. So how do I modify my FileEdit to only show the name once?
If I remove the ChildContent I don't get the filename at all.

**Comment by hesuruio** [comment]
Thanks @stsrki for the reply!
So how do I modify my FileEdit to only show the filename once? If I remove the ChildContent I don't get the filename at all.

**Comment by stsrki** [comment]
Well it seems you're right. I have re-checked everything and Bootstrap implementation indeed have duplicate ChildContent. I'm sorry about that. I will remove it for next release.

**Comment by hesuruio** [comment]
Thanks @stsrki!
Yeah something seemed fishy somewhere.
