### ISSUE TITLE
Size Helpers

### ISSUE THREAD

**Issue by N8Lentz** [stsrki/Blazorise#900]
**Describe the bug**
I am attempting to use the `Size="Size.ExtraLarge"` Helper to make a <check> larger. This functionality works great for `Size="ButtonSize.Large"`. 

**To Reproduce**

```cshtml
<Check  Size="Size.ExtraLarge"></Check>
<Button Size="ButtonSize.Small" Color="Color.Danger">Click me</Button>
<Button Size="ButtonSize.None" Color="Color.Danger">Click me</Button>
<Button Size="ButtonSize.Large" Color="Color.Danger">Click me</Button>
```

**Expected behavior**
I expect the component to refactor its size with the corresponding Size

**Screenshots**

![image](https://user-images.githubusercontent.com/65310934/82088437-5b1c8a00-96b7-11ea-85f6-d998b3226a77.png)

**Additional context**
Thanks, again. 
Really loving these components. Keep up the great work!

**Comment by N8Lentz** [comment]
//<Check TValue="bool" Size="Size.ExtraLarge"></Check>
                //<Button Size="ButtonSize.Small" Color="Color.Danger">Click me</Button>
                //<Button Size="ButtonSize.None" Color="Color.Danger">Click me</Button>
                //<Button Size="ButtonSize.Large" Color="Color.Danger">Click me</Button>

Seems HTML liked that and didnt show the code.

**Comment by stsrki** [comment]
Unfortunately Size should not be there, at least for `<Check>` component. Since most of the input fields inherit base class, Size has also being inherited by mistake.

I should consider replacing Size on input fields with something less generic, like TextSize, DateSize, etc. and add them to only those components that actually can be sized. Either that, or I would need to modify css for all of the input fields to support things like ExtraLarge or ExtraSmall.

**Comment by N8Lentz** [comment]
Thanks for the explanation. 
It would be a nice feature to have available. Maybe in the future?

**Comment by stsrki** [comment]
I will reopen this issue as its definitely needs to be fixed.

**Comment by stsrki** [comment]
This feature has being done with #1147
