### ISSUE TITLE
SelectEdit Binding Bug

### ISSUE THREAD

**Issue by carlosast** [stsrki/Blazorise#93]
f you use bind-SelectedValue the SelectedValue event does not fire.
Also, if using TValue = "string", SelectEdit tries to use int

**Comment by stsrki** [comment]
Regarding the `bind-SelectedValue`. That event is still using `Action` instead of `EventCallback` because of the bug in Blazor. see [#8385](https://github.com/aspnet/AspNetCore/issues/8385)
Fow now you should use `SelectedValue` and `SelectedValueChanged` and fire StateHasChanged manually instead of `bind-` attribute until the bug is fixed. Hopefully it will be fixed soon.

Example: [docs](https://blazorise.com/docs/components/select/#with-event)

As of your second problem, it shouldn't behave like that. Can you give me full code example how you use the SelectEdit so I can test it?

**Comment by carlosast** [comment]
I was able to solve it, thanks.
