### ISSUE TITLE
DataGrid: Sorting with data retrieved in ReadData event not working

### ISSUE THREAD

**Issue by njannink** [stsrki/Blazorise#930]
I'm using the following code in the DataGrid `Data="@Items" ReadData="OnReadData"`

```
public List<ProjectModel> Items { get; set; }

async Task OnReadData(DataGridReadDataEventArgs<ProjectModel> e)
{
        var skip = e.PageSize * (e.Page - 1);
        var take = e.PageSize;

        Items = await HttpClient.GetJsonAsync<List<ProjectModel>>($@"/api/v2/projects/me?skip={skip}&take={take}");

        StateHasChanged();
}
```

With this code sorting doesn't work, but the items are visible. When I load the data in the `InitializeAsync` of the page then sorting works as expected

**Comment by njannink** [comment]
I now see that I need to implement the sorting and filtering myself when readmode is Manual, but it would be nice if default client-side sorting and filtering would be possible anyway like it is when using non manual mode

**Comment by stsrki** [comment]
There is no way to sort on client when in manual mode. You could have millions of records on your back-end. When you navigate to N page you must know what sorting to apply so that you can get the right data. That's why I only provide the information on what to sort and what data need to be returned, based on the offset and length.
