### ISSUE TITLE
CheckEdit nullable value

### ISSUE THREAD

**Issue by carlosast** [stsrki/Blazorise#97]
CheckEdit does not work with nullable boolean?

**Comment by stsrki** [comment]
I remember there was an issues with nullable values for check input in Blazor. Maybe they fixed it but I will need to investigate.

**Comment by stsrki** [comment]
Can you tell what is the reason to have nullable checkbox. How would you handle the behaviour of nullable checkbox? It can be true or false. But what about the null value? Is it going to be unchecked or maybe it's going to be in _intermediate_ state? [example](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox#Indeterminate_state_checkboxes)

The problem is if I add the nullable to CheckEdit than the bindings will not work for non-null variables. And if I convert CheckEdit to generic component than it adds unnecessary complexity because it can only be true or false so there is no reason to make it accept other types through generic argument.

**Comment by carlosast** [comment]
I have classes with properties "bool?"
No problem the checkbox only treats not nulls, the problem is that it gives error when using bind-Checked with "bool?" properties

**Comment by stsrki** [comment]
Yes I know and that is the problem. There are three ways that I can handle this:

1. Convert `Checked` attribute to `bool?`. Doing this it will **stop** working for regular `bool` types.
2. Convert `CheckEdit` to generic component. This will work for the most part but then there are two issues. First the users would need to define _TValue_, and second the `CheckedChanged `would not work because of this issue [#8385](https://github.com/aspnet/AspNetCore/issues/8385)
3. Introduce additional `NullableChecked` attribute to `CheckEdit`. This will leave everything intact and will be used only when needed.

I think the third option will be the best for now, until the issues with generics is fixed. What do you think?
