### ISSUE TITLE
Is it possible to put an image in the datagrid Header instead of a string for the caption? similar to the newcommand in the datagridcommandcolumn. 

### ISSUE THREAD

**Issue by cherron4113** [stsrki/Blazorise#982]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Example: I am trying to do [...] but [...]

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Include any alternative solutions you've considered.

**Comment by stsrki** [comment]
I was sure this was supported but when I checked the source I realized there are no templates for header cells. It should not be a problem to implement.

**Comment by AjaxSantos** [comment]
Swaping type of Caption to RenderingFragment could raise problems at some projects, because projects would not compile ([String input for RenderingFragment](https://github.com/dotnet/aspnetcore/issues/20068)). Maybe create a new property names CaptionTemplate with type RenderingFragment<DataGridColumn>?

**Comment by stsrki** [comment]
My plan is to just add additional template for DataGrid header, Just like there is display or edit templates for grid cells.

**Comment by AjaxSantos** [comment]
Maybe like this #1085 ?

**Comment by stsrki** [comment]
@AjaxSantos Exactly! :)
