### ISSUE TITLE
Feature request: Integrate/support FluentValidation

### ISSUE THREAD

**Issue by StefH** [stsrki/Blazorise#995]
It would be very cool if https://fluentvalidation.net/ support will be added to Blazorise !

Currently there is already a blazor project : https://github.com/Blazored/FluentValidation, maybe you can use this as a start ?

(I'm also checking what needs to be updated / added in this library to integrate....)

**Comment by stsrki** [comment]
#996

**Comment by stsrki** [comment]
Hi @StefH, I hope you're feeling well.

Here I wanted to let you know that I'm working on upgrading validation so that it's more flexible. And in doing so to support fluent validation.

So far I managed to _modularise_ validation component in a way that I have created an interface `IValidationHandler`. It looks like this:

```cs
public interface IValidationHandler
{
    void Validate( IValidation validation, object newValidationValue );
}
```

And I implemented all current validation mechanisms with it. The idea is to be able to use DI to modify actual handlers and to add custom handlers if needed. This way you can implement your own handler and once inject into DI it will be pick up by the Blazorise Validation and it will be used to validate a value.

For example, this is the implementation of the current `Validator` methods:

```cs
public class ValidationValidatorHandler : IValidationValidatorHandler
{
    public void Validate( IValidation validation, object newValidationValue )
    {
        validation.NotifyValidationStarted();

        var validatorEventArgs = new ValidatorEventArgs( newValidationValue );

        validation.Validator?.Invoke( validatorEventArgs );

        var matchMessages = validatorEventArgs.Status == ValidationStatus.Error && !string.IsNullOrEmpty( validatorEventArgs.ErrorText )
            ? new string[] { validatorEventArgs.ErrorText }
            : null;

        if ( validation.Status != validatorEventArgs.Status || ( validation.Messages?.ToArray()?.AreEqual( matchMessages ) == false ) )
        {
            validation.NotifyValidationStatusChanged( validatorEventArgs.Status, matchMessages );
        }
    }
}
```

The same thing can be done for fluent validation

```cs
public class ValidationFluentHandler : IValidationCustomHandler
{
    public void Validate( IValidation validation, object newValidationValue )
    {
        // do the magic here
    }
}
```

## Left

The only thing I'm not sure about is how to make Validation component to **prefer** or **force** this new custom handler when validation occurs. My idea is to have it like:

1. `<Validation Method="ValidationMethod.Custom" />` Can be used to strictly define any supported method.

or

2. `<Validation CustomMethod="true" />` Can be used to force only one, custom method.

So, what do you think of this? Do you have any better ideas or suggestions? Thanks

**Comment by stsrki** [comment]
**Update:**

3. Might be the most flexible solution so far `<Validation HandlerType="typeof(IFluentValidationHandler)" />`

With this solution, we can define as many handler types we need.

**Comment by techierathore** [comment]
This is awesome @stsrki , How Can we test this if we have to ?

**Comment by stsrki** [comment]
@techierathore Only way to test is to clone a repo and then add project references manually instead of using NuGets. Like

```
<ItemGroup>
    <ProjectReference Include="..\..\..\..\..\UI\Blazorise\Source\Blazorise\Blazorise.csproj" />
    <ProjectReference Include="..\..\..\..\..\UI\Blazorise\Source\Extensions\Blazorise.DataGrid\Blazorise.DataGrid.csproj" />
    <ProjectReference Include="..\..\..\..\..\UI\Blazorise\Source\Extensions\Blazorise.Snackbar\Blazorise.Snackbar.csproj" />
  </ItemGroup>
```

If you wish to go that road I will commit the latest changes for testing 😅

**Comment by techierathore** [comment]
Sorry I will wait for the MyGet release then 😅😅

**Comment by stsrki** [comment]
@techierathore Fair enough 😂
